import assert from 'node:assert/strict';
import {newCareer,careerAction,advanceCareer,validCareer,INQUIRIES,PLANS,day,jobMissing,dailyOverhead} from '../lib/career.ts';
const act=(g,a)=>{const r=careerAction(g,a);assert.equal(r.ok,true,r.message);assert.ok(validCareer(r.state),'valid after '+a.type);return r.state;};
const accept=(g,template,plan,engineering='inhouse')=>{const offer=g.offers.find(o=>o.template===template),t=INQUIRIES.find(t=>t.id===template);assert.ok(offer,template+' offered');return act(g,{type:'accept',offer:offer.id,item:PLANS[plan].output,plan,terms:'standard',engineering});};
let g=newCareer();assert.ok(validCareer(g));assert.equal(g.cash,25000);assert.equal(g.equipment.length,0);
g=act(g,{type:'buyMachine',machine:'hobber',used:true,bay:0});g=accept(g,'farm-spares','rough');let j=g.jobs[0];const id=j.id;assert.equal(g.cash,25000-4420+j.deposit);
g=act(g,{type:'supplyJob',id,express:false});assert.equal(jobMissing(g,g.jobs[0]).length,0,'Ordered materials cannot be ordered twice');g=act(g,{type:'release',id});g=advanceCareer(g,16);j=g.jobs.find(j=>j.id===id);assert.equal(j.stage,'complete');assert.equal(g.equipment.length,1);assert.ok(g.cash>25000-4420,'First order earns usable capital');assert.equal(g.drawings[0].runs,1);assert.equal(g.delivered,1);assert.ok(g.offers.some(o=>o.template==='farm-spares'&&o.repeat));assert.ok(validCareer(g));
const firstCost=j.cost;g=accept(g,'farm-spares','rough');j=g.jobs.find(j=>j.stage!=='complete');assert.equal(j.engineeringTotal,.4,'Repeat drawing cuts engineering review time');g=act(g,{type:'supplyJob',id:j.id,express:false});g=act(g,{type:'release',id:j.id});g=advanceCareer(g,16);assert.equal(g.delivered,2);assert.equal(g.equipment[0].completed,24);assert.ok(validCareer(g));
// Staff and retained business assets persist across days; payroll recurs.
g=act(g,{type:'hire',role:'machinist'});const overhead=dailyOverhead(g),before=g.cash;g=advanceCareer(g,8);assert.equal(g.cash,before-overhead);assert.equal(g.people.length,1);
// Engineering-only services can start a business without buying a production machine.
let design=newCareer();design=act(design,{type:'facility',facility:'cad'});design=act(design,{type:'hire',role:'engineer'});design=accept(design,'concept-drive','industrialOut');const designId=design.jobs[0].id;design=act(design,{type:'release',id:designId});design=advanceCareer(design,32);assert.equal(design.jobs[0].stage,'complete');assert.equal(design.equipment.length,0);assert.ok(design.drawings.some(d=>d.origin==='design'));assert.ok(validCareer(design));
// A reverse-engineering job must resolve the sample before any gear cutting starts.
let reverse=newCareer();reverse=accept(reverse,'obsolete-gear','shavedSub');const reverseId=reverse.jobs[0].id;reverse=act(reverse,{type:'buyMachine',machine:'hobber',used:true,bay:0});reverse=act(reverse,{type:'supplyJob',id:reverseId,express:false});reverse=act(reverse,{type:'release',id:reverseId});reverse=advanceCareer(reverse,3);assert.equal(reverse.jobs[0].stage,'engineering');assert.equal(reverse.work.length,0,'No drawing means no released production');reverse=act(reverse,{type:'engineeringMode',id:reverseId,mode:'partner'});reverse=advanceCareer(reverse,32);assert.equal(reverse.jobs[0].stage,'complete');assert.ok(reverse.drawings.some(d=>d.origin==='reverse'));assert.ok(validCareer(reverse));
// House production becomes inventory, not phantom customer income or reputation.
let house=newCareer();house=act(house,{type:'buyMachine',machine:'hobber',used:true,bay:0});house=act(house,{type:'stockLot',item:'rough',qty:10,plan:'rough'});const houseId=house.jobs[0].id;house=act(house,{type:'supplyJob',id:houseId,express:false});house=act(house,{type:'release',id:houseId});house=advanceCareer(house,16);assert.equal(house.inventory.rough,10);assert.equal(house.revenue,0);assert.equal(house.reputation,0);assert.equal(house.delivered,0);house=act(house,{type:'sellStock',item:'rough',qty:5});assert.equal(house.inventory.rough,5);assert.equal(house.revenue,1300);assert.ok(validCareer(house));
// Time partitions and persisted in-process stock must produce the same result.
let seed=newCareer();seed=act(seed,{type:'buyMachine',machine:'hobber',used:true,bay:0});seed=accept(seed,'farm-spares','rough');seed=act(seed,{type:'supplyJob',id:seed.jobs[0].id,express:false});seed=act(seed,{type:'release',id:seed.jobs[0].id});const full=advanceCareer(seed,8);let pieces=structuredClone(seed);for(let i=0;i<80;i++)pieces=advanceCareer(pieces,.1);assert.deepEqual(pieces,full);assert.deepEqual(advanceCareer(JSON.parse(JSON.stringify(full)),8),advanceCareer(full,8));
assert.equal(careerAction(newCareer(),{type:'borrow',amount:-10}).ok,false);assert.equal(careerAction(newCareer(),{type:'stockLot',item:'rough',qty:5,plan:'__proto__'}).ok,false);assert.equal(validCareer({...newCareer(),cash:-1}),false);
console.log('Career checks passed: persistent company growth, repeat drawings, recurring payroll, engineering services, reverse-engineering gate, house-stock production, deterministic time and in-progress reload.');
// Bought-in assembly is a viable independent company path, with persistent staff.
let assembly=newCareer();assembly=act(assembly,{type:'buyMachine',machine:'assembly',used:true,bay:1});assembly=act(assembly,{type:'hire',role:'assembler'});assembly=accept(assembly,'bench-assembly','utilityBuy');const assemblyId=assembly.jobs[0].id;assembly=act(assembly,{type:'supplyJob',id:assemblyId,express:false});assembly=act(assembly,{type:'release',id:assemblyId});assembly=advanceCareer(assembly,24);assert.equal(assembly.delivered,1);assert.equal(assembly.equipment.length,1);assert.equal(assembly.equipment[0].type,'assembly');assert.equal(assembly.people.length,1);assert.ok(assembly.cash>7000);assert.ok(validCareer(assembly));
// The owner cannot operate two machines simultaneously; a hire opens real capacity.
let parallel=newCareer();parallel=act(parallel,{type:'buyMachine',machine:'hobber',used:true,bay:0});parallel=act(parallel,{type:'buyMachine',machine:'hobber',used:true,bay:1});parallel=act(parallel,{type:'stockLot',item:'rough',qty:20,plan:'rough'});const pId=parallel.jobs[0].id;parallel=act(parallel,{type:'supplyJob',id:pId,express:false});parallel=act(parallel,{type:'release',id:pId});parallel=advanceCareer(parallel,2.05);assert.equal(parallel.work.length,1);parallel=act(parallel,{type:'hire',role:'machinist'});assert.equal(parallel.work.length,2);assert.equal(new Set(parallel.work.map(w=>w.worker)).size,2);assert.ok(validCareer(parallel));
// Repeated production grows one company without expiring assets or breaking save limits.
let long=newCareer();long=act(long,{type:'buyMachine',machine:'hobber',used:true,bay:0});for(let i=0;i<90;i++){long=accept(long,'farm-spares','rough');const job=long.jobs.find(j=>j.stage==='planning');long=act(long,{type:'supplyJob',id:job.id,express:false});long=act(long,{type:'release',id:job.id});long=advanceCareer(long,16);assert.equal(long.jobs.find(j=>j.id===job.id).stage,'complete');assert.ok(validCareer(long),'save valid after lot '+i);}assert.equal(long.delivered,90);assert.equal(long.equipment.length,1);assert.equal(long.jobs.length,80);assert.equal(long.drawings[0].runs,90);assert.ok(long.cash>250000);assert.ok(JSON.stringify(long).length<600000);assert.ok(long.offers.find(o=>o.template==='farm-spares').qty>12);
// Cash pressure creates recoverable arrears, not a reset or negative cash.
let bills=newCareer();bills=act(bills,{type:'hire',role:'engineer'});bills={...bills,cash:10};bills=advanceCareer(bills,8);assert.equal(bills.cash,0);assert.equal(bills.arrears,370);const assets=JSON.stringify(bills.people);bills=act(bills,{type:'borrow',amount:1000});assert.equal(bills.arrears,0);assert.equal(bills.cash,630);assert.equal(bills.debt,1000);assert.equal(JSON.stringify(bills.people),assets);assert.ok(validCareer(bills));
console.log('Long-term business checks passed: bought-in assembly, shared labor capacity, 90 retained repeat jobs, growing lot sizes, stable save size, and recoverable cash-flow pressure.');
