import assert from 'node:assert/strict';
import {fresh, act, tick, LINES, GOALS, payout, multiplier, prestigePoints, validGame, autoRate} from '../lib/game.ts';
const t = 1_700_000_000_000;
const run = (g, type, index, now=t, count=1) => act(g, {type,index,count}, now);
let g=fresh(t);
assert.equal(validGame(g),true);
assert.equal(run(g,'automate',0).ok,false);
assert.equal(run(g,'unlock',2).ok,false);
g=run(g,'run',0).game;
assert.equal(tick(g,t+1499).cash,12);
g=tick(g,t+1500);
assert.equal(g.cash,16);
assert.equal(g.lines[0].running,false);
assert.equal(tick(g,t+150000).cash,16,'Manual lines pay only once');
g.cash=10000;
g=run(g,'automate',0,t+1500).game;
const before=g.cash;
g=tick(g,t+1500+15000);
assert.equal(g.cash-before,40,'Ten automated batches');
assert.equal(autoRate(g),4/1.5);
let offline=fresh(t); offline.lines[0].auto=true;
assert.equal(tick(offline,t+36000000).cash-12,76800,'Offline cap is eight hours');
let boosted=act(offline,{type:'boost'},t).game;
assert.equal(tick(boosted,t+15000).cash-12,104,'Only first 12 seconds get triple speed');
assert.equal(act(boosted,{type:'boost'},t+1000).ok,false,'Boost cooldown');
let rich=fresh(t); rich.cash=1e10;
rich=run(rich,'upgrade',0,t,9).game;
assert.equal(rich.lines[0].level,10);
assert.equal(payout(rich,0),80);
assert.equal(multiplier(25),4);
assert.equal(multiplier(200),32);
rich=run(rich,'claim',0).game;
assert.equal(run(rich,'claim',0).ok,false,'No duplicate rewards');
assert.equal(run(rich,'research',0).ok,true);
rich=run(rich,'research',0).game;
assert.equal(run(rich,'research',0).ok,false,'No duplicate research');
const bad=structuredClone(rich); bad.cash=Infinity;
assert.equal(validGame(bad),false);
assert.equal(validGame({...rich, lines:[]}),false);
assert.equal(run(rich,'unlock',90).ok,false);
assert.equal(run(rich,'upgrade',-1).ok,false);
rich.runEarned=4000000; rich.allEarned=7000000;
assert.equal(prestigePoints(rich),2);
const next=act(rich,{type:'prestige'},t).game;
assert.equal(next.points,2);
assert.equal(next.cash,12);
assert.equal(next.lines[0].level,1);
assert.equal(next.research.some(Boolean),false);
assert.equal(next.allEarned,7000000);
assert.equal(payout(next,0),6);
assert.equal(validGame(next),true);
// All lines can unlock, automate, and produce without invalid state.
for(let i=1;i<LINES.length;i++) rich=run(rich,'unlock',i).game;
for(let i=0;i<LINES.length;i++) rich=run(rich,'automate',i).game;
assert.equal(rich.lines.filter(l=>l.auto).length,6);
assert.equal(validGame(tick(rich,t+28800000)),true);
// Frequent ticks match one elapsed calculation without multiplying payouts.
let small=structuredClone(offline);
for(let n=1;n<=1500;n++) small=tick(small,t+n*10);
assert.equal(small.cash,tick(offline,t+15000).cash);
console.log('Game checks passed: manual/automatic batches, offline cap, boost expiry, unlock order, milestones, research, prestige, and malformed saves.');
