'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {Cog,Factory,Truck,Flame,Drill,Wrench,Package,ArrowRight,ArrowUpRight,LockKeyhole,Check,Users,Play,Pause,Plus,Clock3,BookOpen,CloudCheck,LoaderCircle,X,ShoppingCart,ClipboardList,Warehouse,Activity,Settings2} from 'lucide-react';
import {Toaster} from 'sonner';
import {Progress} from '@/components/ui/progress';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {CASH,ITEMS,ITEM_IDS,MACHINES,MACHINE_IDS,RECIPES,PLANS,ORDERS,stock,incoming,nodeStock,queueSize,equipmentCost,missingMachines,planMaterials,planCost,shortage,isShopAction,cycleSeconds,isVendor,type ItemId,type MachineId,type NodeId,type Shop,type Move,type ShopAction} from '@/lib/shop';
import {useShop} from '../use-shop';
import {CellControls,LogisticsSettings,RouteCompare,Stockroom,DispatchBoard} from '../shop-details';
import '../shop.css';

const POS:Record<NodeId,{x:number;y:number}>= {
 receiving:{x:142,y:132},lathe:{x:424,y:132},hobber:{x:706,y:132},shaver:{x:988,y:132},
 partner:{x:142,y:426},outside:{x:424,y:426},carburizer:{x:706,y:426},grinder:{x:988,y:426},
 mill:{x:142,y:720},nitrider:{x:424,y:720},assembly:{x:706,y:720},shipping:{x:988,y:720}
};
const ICONS={lathe:Settings2,mill:Drill,partner:Truck,hobber:Drill,shaver:Cog,outside:Truck,carburizer:Flame,grinder:Settings2,nitrider:Flame,assembly:Wrench,receiving:Warehouse,shipping:Package};
function pathPoints(from:NodeId,to:NodeId){const a=POS[from],b=POS[to];const exit=a.y===132?280:a.y===720?573:b.y<a.y?280:573;const entry=b.y===132?280:b.y===720?573:a.y<b.y?280:573;return exit===entry?[a,{x:a.x,y:exit},{x:b.x,y:entry},b]:[a,{x:a.x,y:exit},{x:1102,y:exit},{x:1102,y:entry},{x:b.x,y:entry},b];}
function movePath(from:NodeId,to:NodeId){return pathPoints(from,to).map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');}
function movePoint(m:Move,now:number){const points=pathPoints(m.from,m.to),lengths=points.slice(1).map((p,i)=>Math.hypot(p.x-points[i].x,p.y-points[i].y));let d=Math.max(0,Math.min(1,(now-m.start)/(m.end-m.start)))*lengths.reduce((n,v)=>n+v,0);for(let i=0;i<lengths.length;i++){if(d<=lengths[i]&&lengths[i]>0){const f=d/lengths[i];return{x:points[i].x+(points[i+1].x-points[i].x)*f,y:points[i].y+(points[i+1].y-points[i].y)*f};}d-=lengths[i];}return points.at(-1)!;}
function status(g:Shop,id:MachineId){const s=g.stations[id];if(!s.count)return 'Empty bay';if(s.paused)return s.jobs.length?'Paused · finishing active jobs':'Paused';if(s.jobs.length)return s.jobs.every(j=>j.start>g.last)?'Material arriving':`${s.jobs.length} of ${s.count} working`;if(s.queue.length)return shortage(g,s.queue[0].recipe);if(s.auto)return stock(g,RECIPES[s.recipe].output)>=s.limit?'Output buffer full':shortage(g,s.recipe);return 'Ready for a job';}
function seconds(v:number){return Math.max(0,Math.ceil(v/1000))+'s';}
type ContextAPI={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};

export default function GearWorks(){
 const {game:g,ref,loaded,loadError,saveError,status:saveStatus,conflict,away,setAway,act,load,save}=useShop();
 const [selected,setSelected]=useState<NodeId>('hobber');const [quantity,setQuantity]=useState(5);const [plan,setPlan]=useState('rough');const [tab,setTab]=useState('routes');const [guide,setGuide]=useState(false);
 const buying=ITEM_IDS.filter(i=>ITEMS[i].buy);const selling=ITEM_IDS.filter(i=>ITEMS[i].sell);const activeJobs=MACHINE_IDS.reduce((n,id)=>n+g.stations[id].jobs.length,0);const workQueue=MACHINE_IDS.reduce((n,id)=>n+queueSize(g.stations[id]),0);
 const currentPlan=PLANS[plan];const missing=missingMachines(g,plan);const raw=planMaterials(plan,quantity);const materialCost=Object.entries(raw).reduce((n,[i,q])=>n+Math.max(0,q!-stock(g,i as ItemId)-incoming(g,i as ItemId))*ITEMS[i as ItemId].buy,0);const routeCrewCost=[...new Set(currentPlan.steps.map(([r])=>RECIPES[r].machine))].reduce((n,id)=>n+(g.stations[id].crew?0:MACHINES[id].crew),0);
 const station=selected!=='receiving'&&selected!=='shipping'?g.stations[selected]:null;const machine=selected!=='receiving'&&selected!=='shipping'?MACHINES[selected]:null;
 const selectedRecipe=station?RECIPES[station.recipe]:null;
 const selectTab=(name:string)=>{setTab(name);document.getElementById('shop-desk')?.scrollIntoView({behavior:'smooth',block:'start'});};
 const selectNode=(id:NodeId,scroll=false)=>{setSelected(id);if(scroll||window.innerWidth<1000)requestAnimationFrame(()=>document.getElementById('shop-inspector')?.scrollIntoView({behavior:'smooth',block:'start'}));};
 const perform=(a:ShopAction)=>{if(!conflict)act(a);};
 useEffect(()=>{
  const context=(document as Document&{modelContext?:ContextAPI}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const register=(tool:Parameters<ContextAPI['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:'read_machine_shop',title:'Read machine shop',description:'Inspect inventory, cash, work queues, machine crews, and parts moving between stations.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({cash:ref.current.cash,revenue:ref.current.revenue,inventory:Object.fromEntries(ITEM_IDS.map(i=>[i,stock(ref.current,i)])),stations:ref.current.stations,movements:ref.current.moves,recipes:RECIPES,plans:PLANS})});
  register({name:'operate_machine_shop',title:'Operate machine shop',description:'Buy machinery or stock, queue a manufacturing route, hire crews, change repeat recipes, dispatch goods, or fill an order. Uses the same shop state and funds as the visible controls.',inputSchema:{type:'object',properties:{type:{type:'string',enum:['install','hire','toggleAuto','clearQueue','selectRecipe','queue','plan','supplyPlan','automatePlan','buy','sell','restock','autosell','keep','hireBuyer','hireClerk','order','pause','upgrade','sellMachine','queueMode','priority','removeJob','buffer','reorder','target','reserve','handling','return']},machine:{type:'string',enum:MACHINE_IDS},recipe:{type:'string',enum:Object.keys(RECIPES)},plan:{type:'string',enum:Object.keys(PLANS)},item:{type:'string',enum:ITEM_IDS},quantity:{type:'integer',minimum:0,maximum:10000},id:{type:'integer',minimum:1},express:{type:'boolean'},enabled:{type:'boolean'},index:{type:'integer',minimum:0,maximum:ORDERS.length-1}},required:['type'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input)=>{if(!isShopAction(input))throw new Error('Invalid shop action.');return act(input);}});
  return()=>lifecycle.abort();
 },[act,ref]);
 return <main className="shop-shell"><Toaster theme="dark" richColors position="bottom-center"/>
  <header className="shop-header"><a href="/idle" className="shop-brand"><span className="shop-mark"><Cog size={29}/></span><span>NIGHT SHIFT<small>GEAR WORKS</small></span></a><div className="shop-header-right"><span className="shop-save"><CloudCheck size={15}/>{saveStatus}</span><button className="shop-small-button" onClick={()=>setGuide(!guide)} aria-expanded={guide}><BookOpen size={16}/>Shop guide</button><a href="/" className="shop-classic">Process design</a></div></header>
  {guide&&<section className="shop-guide"><button aria-label="Close guide" onClick={()=>setGuide(false)}><X size={19}/></button><h2>You run the material flow.</h2><div><p><strong>1. Cut and sell.</strong> Install the hobber. Queue unfinished gear sets and sell them from the stockroom, or deliver five to County Machinery for a better price.</p><p><strong>2. Add value.</strong> Shave soft gears. For case-hardened precision gears, carburize first and grind afterward. The nitriding route uses preconditioned 4140, with finish grinding before treatment.</p><p><strong>3. Build reducers.</strong> Utility reducers accept catalog or shaved gears. Industrial units use commercial hardened gears. Mixed-stage units combine a ground set with a bought set. Heavy-duty units need two nitrided sets.</p><p><strong>4. Automate.</strong> Crews repeat one recipe or a route mix. A buyer replenishes to your stock targets; a clerk sells excess stock. Keep enough intermediate stock for downstream machines and customer orders.</p></div><p className="shop-guide-foot">One gear set is a matched pinion and wheel. Turn your own blanks, machine housing castings, buy part-finished gears, or subcontract individual operations. Prices and cycle times are game-balanced; each gear set is a matched pinion and wheel. Your shop can run for up to 8 hours while you’re away.</p></section>}
  {!loaded?<section className="shop-loading"><Cog size={48}/><h1>{loadError?'Your shop is waiting.':'Opening the shop…'}</h1><p>{loadError||'Checking inventory and work in progress.'}</p>{loadError?<div><button className="shop-primary" onClick={()=>void load()}>Try again</button>{loadError.includes('sign in')&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>}</div>:<LoaderCircle className="spin"/>}</section>:<>
   {saveError&&<div className="shop-error" role="alert"><span>{saveError}</span><button onClick={()=>conflict?location.reload():void save()}>{conflict?'Reload shop':'Retry save'}</button></div>}
   {away&&<div className="shop-away"><div><strong>The night crew checked in.</strong><span>{away.sets} operations finished · {CASH(away.cash)} shipped · {away.minutes} minutes away. Production stopped wherever supplies or cash ran out.</span></div><button onClick={()=>setAway(null)} aria-label="Dismiss offline report"><X size={18}/></button></div>}
   <section className="shop-toolbar"><div className="shop-cash"><span>WORKING CAPITAL</span><strong>{CASH(g.cash)}</strong></div><div className="shop-stat"><span>SALES TO DATE</span><strong>{CASH(g.revenue)}</strong></div><div className="shop-stat"><span>ON THE MACHINES</span><strong>{activeJobs}<small> jobs</small></strong></div><div className="shop-stat"><span>WAITING FOR WORK</span><strong>{workQueue}<small> sets</small></strong></div><div className="shop-live"><span/>SHOP FLOOR LIVE</div></section>
   <div className="shop-workspace"><section className="shop-floor-panel"><div className="shop-panel-title"><div><span className="shop-eyebrow">FROM BLANKS TO GEARBOXES</span><h1>Your machine shop.</h1></div><div className="shop-map-legend"><span><i style={{background:'#efb55c'}}/>In transit</span><span><i style={{background:'#6fd4bb'}}/>Working</span></div></div><div className="shop-floor-scroll"><div className="shop-floor">
    <div className="shop-zone shop-zone-top">STOCK PREPARATION & SOFT CUTTING</div><div className="shop-zone shop-zone-middle">OUTSIDE PROCESSING & HARD FINISHING</div><div className="shop-zone shop-zone-bottom">HOUSINGS, NITRIDING & ASSEMBLY</div>
    <svg className="shop-floor-lines" viewBox="0 0 1130 855" aria-hidden="true"><path d="M25 280 H1102 V573 H25" className="shop-aisle"/><path d="M25 280 H1102 V573 H25" className="shop-aisle-center"/>{Object.values(POS).map((p,i)=><path key={i} d={`M${p.x} ${p.y===426?280:p.y} V${p.y===132?280:573}`} className="shop-spur"/>)}{g.moves.map(m=><path key={'path'+m.id} d={movePath(m.from,m.to)} className="shop-active-route" stroke={ITEMS[m.item].color}/>)}{g.moves.map(m=>{const p=movePoint(m,g.last);return <g key={m.id} transform={`translate(${p.x},${p.y})`}><circle r="13" fill="#101923" stroke={ITEMS[m.item].color} strokeWidth="2"/><circle r="5" fill={ITEMS[m.item].color}/><text x="15" y="-12" fill={ITEMS[m.item].color} fontSize="13" fontWeight="bold">{m.qty>1?'×'+m.qty:''}</text></g>;})}</svg>
    {(Object.entries(POS)as [NodeId,{x:number;y:number}][]).map(([id,p])=>{const Icon=ICONS[id];const isMachine=id!=='receiving'&&id!=='shipping';const s=isMachine?g.stations[id]:null;const owned=!s||s.count>0;const busy=s&&s.jobs.length>0;const color=isMachine?MACHINES[id].color:id==='receiving'?'#a8b7c8':'#8cddbf';const label=isMachine?MACHINES[id].short:id==='receiving'?'Receiving':'Shipping';return <button key={id} aria-label={`${label}. ${s?status(g,id as MachineId):nodeStock(g,id)+' sets in stock'}`} aria-pressed={selected===id} className={`shop-node ${owned?'':'shop-node-empty'} ${selected===id?'shop-node-selected':''} ${busy?'shop-node-busy':''}`} onClick={()=>selectNode(id)} style={{left:`${p.x/1130*100}%`,top:`${p.y/855*100}%`,'--node-color':color}as CSSProperties}><div className="shop-node-top"><span className="shop-node-icon"><Icon size={24}/></span><span className="shop-node-tag">{s?(s.count?`${s.count} ${isVendor(id as MachineId)?(s.count>1?'SLOTS':'SLOT'):s.count>1?'MACHINES':'MACHINE'}`:'OPEN BAY'):id==='receiving'?'INBOUND':'OUTBOUND'}</span>{!owned&&<LockKeyhole size={13}/>}</div><h3>{label}</h3><p className={busy?'shop-status-active':''}>{s?status(g,id as MachineId):id==='receiving'?`${g.moves.filter(m=>m.kind==='buy').reduce((n,m)=>n+m.qty,0)} sets on order`:`${g.moves.filter(m=>m.kind==='sale').reduce((n,m)=>n+m.qty,0)} sets dispatching`}</p><div className="shop-node-bottom">{s&&!owned?<strong>{CASH(equipmentCost(g,id as MachineId))}</strong>:<span><Package size={12}/>{nodeStock(g,id)} on rack</span>}{s&&owned&&<span>{s.auto?<><Users size={12}/>Repeat</>:queueSize(s)?`${queueSize(s)} queued`:'Manual'}</span>}</div>{busy&&<Progress aria-label={`${label} current cycle`} className="shop-node-progress" value={Math.max(0,Math.min(100,(g.last-s!.jobs[0].start)/(s!.jobs[0].finish-s!.jobs[0].start)*100))}/>}</button>;})}
    </div></div><div className="shop-floor-caption"><span><Activity size={14}/>{g.moves.length?`${g.moves.length} material movement${g.moves.length===1?'':'s'} in progress`:'Select a bay to install a machine or queue work.'}</span><span className="shop-scroll-hint">Scroll sideways to see the full floor</span></div></section>
    <aside id="shop-inspector" className="shop-inspector"><div className="shop-inspector-heading"><span className="shop-eyebrow">{station?'SELECTED CELL':'SHOP LOGISTICS'}</span><h2>{machine?.name||(selected==='receiving'?'Receiving & purchasing':'Shipping & sales')}</h2><p>{machine?.detail||(selected==='receiving'?'Buy stock, finished blanks, part-finished gears, catalog sets, or housing components. Choose standard or express delivery in the stockroom.':'Turn finished stock into cash. A shipping clerk can sell selected products automatically.')}</p></div>
     {station&&machine&&selectedRecipe?<>{!station.count?<div className="shop-install"><div className="shop-price"><span>Equipment investment</span><strong>{CASH(equipmentCost(g,selected as MachineId))}</strong></div><button className="shop-primary" disabled={g.cash<equipmentCost(g,selected as MachineId)||conflict} onClick={()=>perform({type:'install',machine:selected as MachineId})}><Plus size={17}/>Install {machine.short.toLowerCase()}</button><p>Own the machine, then assign its work below.</p></div>:<>
      <div className="shop-recipe-picker"><label>Work recipe</label><Select value={station.recipe} onValueChange={recipe=>perform({type:'selectRecipe',machine:selected as MachineId,recipe})}><SelectTrigger aria-label="Selected cell recipe"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(RECIPES).filter(([,r])=>r.machine===selected).map(([key,r])=><SelectItem key={key} value={key}>{r.name}</SelectItem>)}</SelectContent></Select></div>
      <div className="shop-recipe-bom">{Object.entries(selectedRecipe.input).map(([id,q])=><div key={id}><span className="shop-item-dot" style={{background:ITEMS[id as ItemId].color}}/><span>{q} × {ITEMS[id as ItemId].short}</span><strong className={stock(g,id as ItemId)>=q!?'shop-stock-ok':'shop-stock-short'}>{stock(g,id as ItemId)} in stock</strong></div>)}<div className="shop-output"><ArrowRight size={15}/><span>1 × {ITEMS[selectedRecipe.output].short}</span></div></div>
      <p className="shop-note">{selectedRecipe.note}</p><div className="shop-cycle-meta"><span><Clock3 size={14}/>{cycleSeconds(g,station.recipe).toFixed(1)}s + transfer</span><span>{selectedRecipe.fee?`${CASH(selectedRecipe.fee)} fee / set`:'No processing fee'}</span></div>
      <div className="shop-queue-actions"><button className="shop-primary" disabled={conflict||queueSize(station)+quantity>200} onClick={()=>perform({type:'queue',recipe:station.recipe,quantity})}><Play size={15} fill="currentColor"/>Queue {quantity}</button><div className="shop-quantity">{[1,5,10].map(n=><button key={n} aria-pressed={quantity===n} onClick={()=>setQuantity(n)}>{n}</button>)}</div></div><p className="shop-note">Queued work waits for its inputs. {shortage(g,station.recipe)}.</p>
      <div className="shop-crew-row"><div><strong>Repeat production</strong><span>{station.crew?(station.repeat.length>1?'Crew rotates through this route’s operations.':'Crew follows the selected recipe.'):`Hire a crew for ${CASH(machine.crew)}.`}</span></div>{station.crew?<Switch checked={station.auto} disabled={conflict} onCheckedChange={()=>perform({type:'toggleAuto',machine:selected as MachineId})} aria-label="Repeat selected recipe"/>:<button className="shop-outline" disabled={g.cash<machine.crew||conflict} onClick={()=>perform({type:'hire',machine:selected as MachineId})}><Users size={15}/>Hire</button>}</div>
      {station.jobs.length>0&&<div className="shop-active-jobs">{station.jobs.map(job=><div key={job.id}><div><span>{RECIPES[job.recipe].name}</span><strong>{job.start>g.last?'Loading':seconds(job.finish-g.last)}</strong></div><Progress value={Math.max(0,Math.min(100,(g.last-job.start)/(job.finish-job.start)*100))} aria-label="Job progress"/></div>)}</div>}
      <div className="shop-queue-summary"><span>{queueSize(station)} waiting · {station.completed} completed</span>{station.queue.length>0&&<button onClick={()=>perform({type:'clearQueue',machine:selected as MachineId})}>Clear waiting</button>}</div>
      {<button className="shop-expand" disabled={station.count>=3||g.cash<equipmentCost(g,selected as MachineId)||conflict} onClick={()=>perform({type:'install',machine:selected as MachineId})}><Plus size={15}/>{station.count>=3?'Cell fully equipped':`${isVendor(selected as MachineId)?'Book another slot':'Add another machine'} · ${CASH(equipmentCost(g,selected as MachineId))}`}</button>}
      <CellControls g={g} id={selected as MachineId} perform={perform} disabled={conflict}/>
     </>}</>:<div className="shop-logistics"><div className="shop-price"><span>{selected==='receiving'?'Automatic replenishment':'Automatic sales'}</span><strong>{selected==='receiving'?(g.buyer?'Hired':CASH(900)):(g.clerk?'Hired':CASH(700))}</strong></div><button className="shop-primary" disabled={conflict||(selected==='receiving'?(g.buyer||g.cash<900):(g.clerk||g.cash<700))} onClick={()=>perform({type:selected==='receiving'?'hireBuyer':'hireClerk'})}><Users size={17}/>{selected==='receiving'?(g.buyer?'Buyer on staff':'Hire a buyer'):(g.clerk?'Clerk on staff':'Hire a shipping clerk')}</button><p>{selected==='receiving'?'Select Auto buy beside materials in the stockroom. Set the reorder point and target for each material, and keep cash in reserve for processing fees.':'Select Auto sell for a product and choose how many sets to retain. Downstream jobs get their inputs before excess stock is sold.'}</p><button className="shop-outline" onClick={()=>selectTab('stock')}><Warehouse size={16}/>Open stockroom</button><LogisticsSettings g={g} perform={perform} disabled={conflict}/><div className="shop-rack-preview"><h3>{selected==='receiving'?'Receiving rack':'Ready for sale'}</h3>{(selected==='receiving'?buying:selling).filter(i=>stock(g,i)>0).map(i=><div key={i}><span>{ITEMS[i].short}</span><strong>{selected==='receiving'?g.bins.receiving[i]:stock(g,i)}</strong></div>)}{!(selected==='receiving'?buying:selling).some(i=>stock(g,i)>0)&&<p>The rack is empty.</p>}</div></div>}
    </aside></div>
   <section id="shop-desk" className="shop-desk"><Tabs value={tab} onValueChange={setTab}><div className="shop-desk-header"><TabsList className="shop-tabs"><TabsTrigger value="routes"><Settings2 size={16}/>Production routes</TabsTrigger><TabsTrigger value="stock"><Warehouse size={16}/>Stockroom</TabsTrigger><TabsTrigger value="orders"><ClipboardList size={16}/>Customer orders</TabsTrigger><TabsTrigger value="dispatch"><Truck size={16}/>Dispatch</TabsTrigger><TabsTrigger value="log"><Activity size={16}/>Shop log</TabsTrigger></TabsList><span className="shop-unit-note">Inventory unit: one matched gear set</span></div>
    <TabsContent value="routes"><div className="shop-route-planner"><div className="shop-route-config"><span className="shop-eyebrow">PLAN THE WHOLE ROUTE</span><h2>What are we making?</h2><label className="shop-field-label">Product</label><Select value={currentPlan.output} onValueChange={output=>setPlan(Object.keys(PLANS).find(key=>PLANS[key].output===output)!)}><SelectTrigger className="shop-plan-select" aria-label="Product to manufacture"><SelectValue/></SelectTrigger><SelectContent>{[...new Set(Object.values(PLANS).map(p=>p.output))].map(id=><SelectItem key={id} value={id}>{ITEMS[id].name}</SelectItem>)}</SelectContent></Select><label className="shop-field-label">How to make it</label><Select value={plan} onValueChange={setPlan}><SelectTrigger className="shop-plan-select" aria-label="Production route"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(PLANS).filter(([,p])=>p.output===currentPlan.output).map(([key,p])=><SelectItem key={key} value={key}>{p.name}</SelectItem>)}</SelectContent></Select><p>{currentPlan.desc}</p><div className="shop-route-economics"><div><span>Material + process cost</span><strong>{CASH(planCost(plan))}</strong></div><div><span>Spot sale / unit</span><strong>{CASH(ITEMS[currentPlan.output].sell)}</strong></div><div><span>Margin before equipment / unit</span><strong>{CASH(ITEMS[currentPlan.output].sell-planCost(plan))}</strong></div></div></div>
     <div className="shop-route-detail"><div className="shop-route-chain">{currentPlan.steps.map(([r,q],i)=>{const recipe=RECIPES[r],Icon=ICONS[recipe.machine];return <div className="shop-route-step-wrap" key={r}>{i>0&&<ArrowRight size={18}/>}<button className={`shop-route-step ${g.stations[recipe.machine].count?'':'shop-route-missing'}`} style={{'--node-color':MACHINES[recipe.machine].color}as CSSProperties} onClick={()=>selectNode(recipe.machine,true)}><Icon size={22}/><span>{MACHINES[recipe.machine].short}</span><em>{ITEMS[recipe.output].short}</em><small>{q>1?`${q} sets · `:''}{cycleSeconds(g,r).toFixed(1)}s{g.stations[recipe.machine].count?'':' · not installed'}</small></button></div>;})}</div><div className="shop-route-materials"><strong>For {quantity} {ITEMS[currentPlan.output].short.toLowerCase()}:</strong>{Object.entries(raw).map(([i,q])=><span key={i}>{q} × {ITEMS[i as ItemId].short}<small> {stock(g,i as ItemId)+incoming(g,i as ItemId)} available / incoming</small></span>)}</div><div className="shop-route-buttons"><div className="shop-quantity">{[1,5,10].map(n=><button key={n} aria-pressed={quantity===n} onClick={()=>setQuantity(n)}>{n}</button>)}</div><button className="shop-outline" disabled={!materialCost||g.cash<materialCost||conflict} onClick={()=>perform({type:'supplyPlan',plan,quantity})}><ShoppingCart size={16}/>{materialCost?`Buy missing materials · ${CASH(materialCost)}`:'Materials supplied'}</button><button className="shop-primary" disabled={missing.length>0||conflict} onClick={()=>perform({type:'plan',plan,quantity})}><Play size={16}/>Queue route ×{quantity}</button></div><div className="shop-route-bottom">{missing.length?<p>Equipment needed: {missing.map(id=>`${MACHINES[id].short} (${CASH(equipmentCost(g,id))})`).join(', ')}.</p>:<p>Jobs move automatically to the next operation as material becomes available.</p>}<button className="shop-text-button" disabled={missing.length>0||g.cash<routeCrewCost||conflict} onClick={()=>perform({type:'automatePlan',plan})}><Users size={15}/>{routeCrewCost?`Hire route crews · ${CASH(routeCrewCost)}`:'Set crews to repeat this route'}</button></div></div></div><RouteCompare g={g} plan={plan} setPlan={setPlan}/></TabsContent>
    <TabsContent value="stock"><Stockroom g={g} perform={perform} disabled={conflict} quantity={quantity} setQuantity={setQuantity}/></TabsContent>
    <TabsContent value="dispatch"><DispatchBoard g={g} selectCell={id=>selectNode(id,true)}/></TabsContent>
    <TabsContent value="orders"><div className="shop-orders-heading"><div><h2>Give the finished work a destination.</h2><p>Orders pay more than spot sales and can be filled again after delivery. Keep stock for them or sell it as it comes off the machine.</p></div></div><div className="shop-orders">{ORDERS.map((o,i)=>{const have=stock(g,o.item),moving=g.moves.some(m=>m.order===i);return <article key={o.name} className="shop-order" style={{'--node-color':ITEMS[o.item].color}as CSSProperties}><div className="shop-order-top"><span>{o.buyer}</span><ClipboardList size={19}/></div><h3>{o.name}</h3><p>{o.quantity} × {ITEMS[o.item].name}</p><Progress value={Math.min(100,have/o.quantity*100)} aria-label={`${o.name} stock available`}/><div className="shop-order-count"><span>{have} in stock</span><strong>{CASH(o.pay)}</strong></div><button className="shop-primary" disabled={have<o.quantity||moving||conflict} onClick={()=>perform({type:'order',index:i})}>{moving?'On the truck':`Ship ${o.quantity} ${['utility','industrial','precision','hybrid','heavy'].includes(o.item)?'reducers':'sets'}`}</button><small>{g.orders[i]} deliveries completed · {CASH(o.pay/o.quantity)} / unit</small><button className="shop-text-button" onClick={()=>{setPlan(Object.keys(PLANS).find(key=>PLANS[key].output===o.item)!);setQuantity(o.quantity);selectTab('routes');}}>Plan this order <ArrowRight size={14}/></button></article>;})}</div></TabsContent>
    <TabsContent value="log"><div className="shop-log"><h2>On the shop clipboard.</h2>{g.log.map(entry=><div key={entry.id}><time>{new Date(entry.time).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</time><span>{entry.text}</span></div>)}</div></TabsContent>
   </Tabs></section><footer className="shop-footer"><span><Cog size={16}/>NIGHT SHIFT · GEAR WORKS</span><a href="/classic">Original factory</a><span>Better gears. Better margins.</span></footer>
  </>}
 </main>;
}
