'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Cog,Play,Pause,FastForward,RotateCcw,Undo2,Plus,Warehouse,Package,Link2,Move,Clock3,Wallet,Target,BookOpen,ClipboardList,Check,CloudCheck,X,Lightbulb,AlertTriangle,Settings2,Star} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {Progress} from '@/components/ui/progress';
import {CASH} from '@/lib/shop';
import {CHALLENGES,MISSIONS,FREEPLAY,ITEMS,ITEM_IDS,MACHINES,RECIPES,STEP,challengeFor,starter,makeCell,outputItem,accepts,cellName,connect,capitalCost,designIssues,newRun,stepRun,finishRun,resultOf,recordResult,unlocked,type Blueprint,type Cell,type Link,type Run,type MachineId,type ItemId,type CellKind} from '@/lib/process';
import {useDesign} from '../use-design';
import {Contracts,Guide,Stars,RunReport,Choice,NumberField} from '../process-panels';
import {ProcessFloor,MACHINE_ICONS} from '../process-floor';
import {ProcessInspector} from '../process-inspector';
import '../process.css';
type ContextAPI={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
export default function ProcessGame(){
 const{data,ref,change,loaded,error,saveError,status,conflict,save,load}=useDesign();
 const b=data.designs[data.mission];const c=useMemo(()=>challengeFor(data.mission,b),[data.mission,b]);
 const[trial,setTrial]=useState<Run|null>(null),trialRef=useRef<Run|null>(null),[running,setRunning]=useState(false),[speed,setSpeed]=useState(4);
 const[selected,setSelected]=useState<number|null>(null),[selectedLink,setSelectedLink]=useState<number|null>(null),[connecting,setConnecting]=useState<number|null>(null),[moving,setMoving]=useState<number|null>(null),[placement,setPlacement]=useState<Cell|null>(null);
 const[contracts,setContracts]=useState(false),[guide,setGuide]=useState(false),[hint,setHint]=useState(-1),[history,setHistory]=useState<Blueprint[]>([]),[showReport,setShowReport]=useState(false);
 const editable=loaded&&!conflict&&!trial;const cost=capitalCost(b),issues=designIssues(b,c),cell=b.cells.find(n=>n.id===selected),link=b.links.find(l=>l.id===selectedLink);
 const last=data.last[data.mission],best=data.best[data.mission];const completeRecorded=useRef(false);
 const clearTools=()=>{setConnecting(null);setMoving(null);setPlacement(null);};
 const editBlueprint=useCallback((next:Blueprint)=>{if(conflict||trialRef.current)return;setHistory(h=>[...h.slice(-29),structuredClone(b)]);change(s=>({...s,designs:{...s.designs,[s.mission]:next}}));},[b,change,conflict]);
 const selectCell=(id:number,scroll=false)=>{if(connecting!==null&&editable){const result=connect(b,connecting,id);if(result.error){toast.error(result.error);return;}editBlueprint(result.blueprint);setConnecting(null);setSelectedLink(result.blueprint.links.at(-1)!.id);setSelected(null);toast.success('Material route connected.');return;}setSelected(id);setSelectedLink(null);if(scroll||window.innerWidth<1000)requestAnimationFrame(()=>document.getElementById('pd-inspector-anchor')?.scrollIntoView({behavior:'smooth',block:'start'}));};
 const selectLink=(id:number)=>{setSelectedLink(id);setSelected(null);clearTools();if(window.innerWidth<1000)requestAnimationFrame(()=>document.getElementById('pd-inspector-anchor')?.scrollIntoView({behavior:'smooth',block:'start'}));};
 const place=(kind:CellKind,machine:MachineId='hobber')=>{if(!editable)return;clearTools();const template=makeCell(0,kind,0,0,machine,kind==='sink'?c.goals[0].item:c.sources[0]);template.lot=c.goals.reduce((n,g)=>n+g.qty,0);setPlacement(template);};
 const moveCell=(id:number,x:number,y:number)=>{if(!editable||b.cells.some(n=>n.x===x&&n.y===y))return;const next=structuredClone(b);const target=next.cells.find(n=>n.id===id);if(!target)return;target.x=x;target.y=y;editBlueprint(next);setMoving(null);setSelected(id);};
 const onEmpty=(x:number,y:number)=>{if(!editable)return;if(moving!==null){moveCell(moving,x,y);return;}if(!placement){setSelected(null);setSelectedLink(null);clearTools();return;}const next=structuredClone(b);const node={...placement,id:next.nextId++,x,y};next.cells.push(node);editBlueprint(next);setSelected(node.id);setSelectedLink(null);setPlacement(null);};
 const changeCell=(patch:Partial<Cell>)=>{if(!cell||!editable)return;const next=structuredClone(b),node=next.cells.find(n=>n.id===cell.id)!;Object.assign(node,patch);const count=next.links.length;next.links=next.links.filter(l=>{const a=next.cells.find(n=>n.id===l.from)!,z=next.cells.find(n=>n.id===l.to)!;return l.item===outputItem(a)&&accepts(z,l.item);});editBlueprint(next);if(next.links.length<count)toast('Incompatible material routes removed.');};
 const changeLink=(patch:Partial<Link>)=>{if(!link||!editable)return;const next=structuredClone(b);Object.assign(next.links.find(l=>l.id===link.id)!,patch);editBlueprint(next);};
 const removeCell=()=>{if(!cell||!editable)return;editBlueprint({...b,cells:b.cells.filter(n=>n.id!==cell.id),links:b.links.filter(l=>l.from!==cell.id&&l.to!==cell.id)});setSelected(null);clearTools();};
 const undo=()=>{if(!editable||!history.length)return;const prior=history.at(-1)!;setHistory(h=>h.slice(0,-1));change(s=>({...s,designs:{...s.designs,[s.mission]:prior}}));setSelected(null);setSelectedLink(null);clearTools();};
 const redesign=()=>{setRunning(false);setTrial(null);trialRef.current=null;completeRecorded.current=false;clearTools();};
 const selectMission=(id:string)=>{const index=MISSIONS.findIndex(c=>c.id===id);if(index<0||!unlocked(ref.current,index)||conflict)return;redesign();setSelected(null);setSelectedLink(null);setHistory([]);setHint(-1);setShowReport(false);change(s=>({...s,mission:id,designs:{...s.designs,[id]:s.designs[id]||starter(MISSIONS[index])}}));};
 const acceptRun=useCallback((r:Run)=>{trialRef.current=r;setTrial(r);if(r.finished){setRunning(false);setShowReport(true);if(!completeRecorded.current){completeRecorded.current=true;change(s=>recordResult(s,s.mission,resultOf(r,b,c)));if(r.success)toast.success('Contract delivered. Your design passed.');else toast('Shift complete. Review the bottlenecks and revise.');}}},[b,c,change]);
 const begin=(instant=false)=>{if(!loaded||conflict)return;if(issues.blocking.length){toast.error(issues.blocking[0]);return;}clearTools();setShowReport(false);completeRecorded.current=false;const r=newRun(b);if(instant){acceptRun(finishRun(r,b,c));}else{acceptRun(r);setRunning(true);}};
 const finish=()=>{if(!loaded||conflict)return;if(!trialRef.current){begin(true);return;}if(!trialRef.current.finished)acceptRun(finishRun(trialRef.current,b,c));};
 useEffect(()=>{if(!running||conflict)return;let previous=performance.now(),credit=0;const tick=setInterval(()=>{const now=performance.now(),elapsed=Math.min(.3,(now-previous)/1000);previous=now;if(document.hidden)return;credit+=elapsed*speed;const steps=Math.floor(credit/STEP);if(steps&&trialRef.current&&!trialRef.current.finished){credit-=steps*STEP;acceptRun(stepRun(trialRef.current,b,c,steps));}},70);return()=>clearInterval(tick);},[running,speed,b,c,acceptRun,conflict]);
 const actionsRef=useRef({finish});actionsRef.current={finish};const blueprintRef=useRef(b);blueprintRef.current=b;
 useEffect(()=>{const context=(document as Document&{modelContext?:ContextAPI}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:Parameters<ContextAPI['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_process_design',title:'Inspect production design',description:'Read the current contract, machines, recipes, material routes, budgets, and production-test results.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({contract:challengeFor(ref.current.mission,blueprintRef.current),blueprint:blueprintRef.current,run:trialRef.current,best:ref.current.best[ref.current.mission]})});register({name:'run_process_trial',title:'Test production design',description:'Run the current floor layout through its simulated shift and save its result, just like Finish test in the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:()=>{actionsRef.current.finish();return trialRef.current;}});return()=>lifecycle.abort();},[ref]);
 const instruction=placement?`Place ${placement.kind==='machine'?MACHINES[placement.machine].short.toLowerCase():placement.kind} in an empty bay.`:moving?`Select an empty bay to move cell #${moving}.`:connecting?`Connect cell #${connecting} to a compatible destination.`:trial?(running?'Production test running. Select any cell or route to inspect the flow.':trial.finished?'Test complete. Review the results, then revise your layout.':'Test paused. Inspect the work in progress or resume.'):b.cells.filter(n=>n.kind==='machine').length===0?'Start by placing a machine. Then connect its input and output.':'Select cells to configure them. Drag to move; use the link button to connect.';
 const restoreBest=()=>{if(!editable||!best)return;editBlueprint(structuredClone(best.blueprint));setSelected(null);setSelectedLink(null);clearTools();toast.success('Best-performing layout restored.');};
 const nextContract=()=>{const i=CHALLENGES.findIndex(v=>v.id===c.id);if(i>=0&&i<CHALLENGES.length-1)selectMission(CHALLENGES[i+1].id);else setContracts(true);};
 const result=trial?.finished?last:null;
 return <main className="pd-app"><Toaster theme="dark" position="bottom-center" richColors/><header className="pd-header"><a className="pd-brand" href="/design"><span><Cog size={25}/></span><div>GEAR WORKS<small>PRODUCTION ENGINEER</small></div></a><div className="pd-header-actions"><span className="pd-save"><CloudCheck size={15}/>{status}</span><button className="pd-secondary" onClick={()=>setContracts(true)} disabled={!loaded}><ClipboardList size={16}/>Contracts</button><button className="pd-icon-button" title="How to play" aria-label="How to play" onClick={()=>setGuide(true)}><BookOpen size={18}/></button><a href="/idle">Previous shop</a></div></header>
 {!loaded?<section className="pd-loading"><Cog size={44}/><h1>{error?'Could not open the design desk.':'Opening your design desk…'}</h1><p>{error||'Loading saved layouts and contracts.'}</p>{error&&<button className="pd-primary" onClick={()=>void load()}>Try again</button>}</section>:<>
 {saveError&&<div className="pd-save-error" role="alert"><span>{saveError}</span><button className="pd-secondary" onClick={()=>conflict?location.reload():void save()}>{conflict?'Reload designs':'Retry save'}</button></div>}
 <section className="pd-brief"><div className="pd-brief-title"><span className="pd-eyebrow">{c.id===FREEPLAY.id?'OPEN WORKSHOP':`CONTRACT ${String(CHALLENGES.findIndex(v=>v.id===c.id)+1).padStart(2,'0')} / ${CHALLENGES.length}`} · {c.client}</span><h1>{c.name}</h1><p>{c.brief}</p></div><div className="pd-goals">{c.goals.map(g=><div key={g.item}><div><span className="pd-item-dot" style={{background:ITEMS[g.item].color}}/><strong>{ITEMS[g.item].short}</strong><span>{trial?.delivered[g.item]||0} / {g.qty}</span></div><Progress value={Math.min(100,(trial?.delivered[g.item]||0)/g.qty*100)} aria-label={`${ITEMS[g.item].short} delivered`}/></div>)}<div className="pd-contract-stars"><Stars n={best?.stars||0}/><span>{best?`Best: ${best.time.toFixed(1)}s · ${CASH(best.cost)}`:'Deliver · beat the clock · cut running cost'}</span></div></div></section>
 {c.id===FREEPLAY.id&&<div className="pd-free-settings"><Choice label="Test product" value={b.goal} disabled={!editable} options={ITEM_IDS.filter(i=>ITEMS[i].sell>0&&!['blank','alloy','kit','heavyKit'].includes(i)).map(i=>({value:i,label:ITEMS[i].name}))} onChange={value=>{const goal=value as ItemId;const next=structuredClone(b);next.goal=goal;for(const sink of next.cells.filter(n=>n.kind==='sink'))sink.item=goal;next.links=next.links.filter(l=>accepts(next.cells.find(n=>n.id===l.to)!,l.item));editBlueprint(next);}}/><NumberField label="Target quantity" value={b.quantity} disabled={!editable} onChange={quantity=>editBlueprint({...b,quantity})}/><p>The full catalog is available. Six hundred simulated seconds per test.</p></div>}
 <section className="pd-command-bar"><div className="pd-budget"><Wallet size={16}/><span>Equipment <strong className={cost>c.capital?'pd-over-budget':''}>{CASH(cost)} <small>/ {CASH(c.capital)}</small></strong></span></div><div className="pd-budget"><Settings2 size={16}/><span>Operations <strong>{CASH(trial?.spent||0)} <small>/ {CASH(c.operating)}</small></strong></span></div><div className="pd-budget"><Clock3 size={16}/><span>Shift <strong>{(trial?.time||0).toFixed(1)}s <small>/ {c.duration}s</small></strong></span></div><div className="pd-playback"><div className="pd-speed" aria-label="Playback speed">{[1,4,16].map(n=><button key={n} aria-pressed={speed===n} onClick={()=>setSpeed(n)}>{n}×</button>)}</div>{trial&&!trial.finished?<button className="pd-primary" disabled={conflict} onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'Pause':'Resume'}</button>:<button className="pd-primary" disabled={conflict||issues.blocking.length>0} onClick={()=>begin()}><Play size={16}/>Run test</button>}<button className="pd-secondary" disabled={conflict||!!trial?.finished||issues.blocking.length>0} onClick={finish} title="Simulate the remaining shift instantly"><FastForward size={16}/>Finish test</button>{trial&&<button className="pd-secondary" disabled={conflict} onClick={redesign}><RotateCcw size={15}/>Edit layout</button>}</div></section>
 <div className="pd-workspace"><section className="pd-floor-panel"><div className="pd-equipment"><span className="pd-eyebrow">PLACE</span><button disabled={!editable} aria-pressed={placement?.kind==='source'} onClick={()=>place('source')}><Warehouse size={16}/><span>Supplier<small>Free</small></span></button>{c.machines.map(id=>{const Icon=MACHINE_ICONS[id];return <button key={id} disabled={!editable} aria-pressed={placement?.kind==='machine'&&placement.machine===id} onClick={()=>place('machine',id)}><Icon size={16}/><span>{MACHINES[id].short}<small>{CASH(MACHINES[id].cost)}</small></span></button>;})}<button disabled={!editable} aria-pressed={placement?.kind==='buffer'} onClick={()=>place('buffer')}><Package size={16}/><span>Buffer rack<small>$120</small></span></button><button disabled={!editable} aria-pressed={placement?.kind==='sink'} onClick={()=>place('sink')}><Target size={16}/><span>Dispatch<small>Free</small></span></button></div>
 <div className="pd-floor-tools"><div><span className={running?'pd-running-dot':'pd-design-dot'}/><strong>{trial?(running?'TEST RUNNING':trial.finished?'TEST COMPLETE':'TEST PAUSED'):'DESIGN MODE'}</strong><span>12 ft grid</span></div><div><button className="pd-text-button" disabled={!editable||!history.length} onClick={undo}><Undo2 size={14}/>Undo</button><button className="pd-text-button" onClick={()=>setHint(h=>(h+1)%c.hints.length)}><Lightbulb size={14}/>Hint</button></div></div>
 <div className="pd-instruction" role="status"><span>{instruction}</span>{(placement||moving||connecting)&&<button onClick={clearTools} aria-label="Cancel tool"><X size={16}/></button>}</div>
 {hint>=0&&<div className="pd-hint"><Lightbulb size={17}/><p>{c.hints[hint]}</p><button aria-label="Dismiss hint" onClick={()=>setHint(-1)}><X size={15}/></button></div>}
 <ProcessFloor b={b} run={trial} selected={selected} selectedLink={selectedLink} connecting={connecting} moving={moving} placing={!!placement} editable={editable} onCell={id=>selectCell(id)} onLink={selectLink} onEmpty={onEmpty} onConnect={id=>{if(!editable)return;clearTools();setConnecting(id);setSelected(id);setSelectedLink(null);}} onMove={moveCell}/>
 <div className="pd-floor-legend"><span><i className="busy"/>Working</span><span><i className="waiting"/>Input starved</span><span><i className="blocked"/>Output blocked</span><small>Independent routes · one unit per cart</small></div>
 {(issues.blocking.length>0||issues.notes.length>0)&&!trial&&<details className="pd-issues" open={issues.blocking.length>0}><summary><AlertTriangle size={15}/>{issues.blocking.length?`${issues.blocking.length} issue${issues.blocking.length===1?'':'s'} must be fixed before testing`:`${issues.notes.length} routing note${issues.notes.length===1?'':'s'}`}</summary>{[...issues.blocking,...issues.notes].map((note,i)=><p key={i}>{note}</p>)}</details>}
 </section><div id="pd-inspector-anchor"><ProcessInspector b={b} c={c} run={trial} cell={cell} link={link} editable={editable} onCellChange={changeCell} onLinkChange={changeLink} onConnect={()=>{if(cell){clearTools();setConnecting(cell.id);}}} onMove={()=>{if(cell){clearTools();setMoving(cell.id);}}} onCopy={()=>{if(cell){clearTools();setPlacement({...cell});}}} onDelete={removeCell} onDeleteLink={()=>{if(link){editBlueprint({...b,links:b.links.filter(l=>l.id!==link.id)});setSelectedLink(null);}}} onSelectCell={id=>selectCell(id)} onSelectLink={selectLink}/></div></div>
 {trial&&<RunReport run={trial} result={result||null} b={b} c={c} onCell={id=>selectCell(id,true)} onEdit={redesign} onNext={nextContract}/>} {!trial&&last&&<section className="pd-last-result">{best&&<button className="pd-secondary" disabled={!editable} onClick={restoreBest}>Restore best layout</button>}<button className="pd-secondary" onClick={()=>setShowReport(!showReport)}>Last test: {last.success?'delivered':'incomplete'} · {last.time.toFixed(1)}s · {CASH(last.cost)} {showReport?'· Hide review':'· Review'}</button>{showReport&&<RunReport run={null} result={last} b={b} c={c} onCell={id=>selectCell(id,true)} onEdit={()=>setShowReport(false)} onNext={nextContract}/>}</section>}
 <footer className="pd-footer"><span>Designs and results save automatically. Every test starts with fresh stock.</span><a href="/idle">Open your previous machine shop</a></footer>
 </>}
 <Contracts open={contracts} setOpen={setContracts} save={data} onSelect={selectMission}/><Guide open={guide} setOpen={setGuide}/>
 </main>;
}
