'use client';
import {useState} from 'react';
import {Plus,Factory,Package,Truck,Settings2} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {MACHINES,MACHINE_IDS,ITEMS,RECIPES,bays,vendor,machinePrice,type Career,type Equipment,type MachineId} from '@/lib/career';
import {Choice,Modal,Bar,money,hours,type Act} from './career-ui';

function MachineArt({type,color,busy}:{type:MachineId;color:string;busy:boolean}){
 const furnace=type==='carburizer'||type==='nitrider',bench=type==='assembly';
 return <g className={busy?'gw-machine-working':''}><ellipse cx="0" cy="35" rx="50" ry="11" fill="#0005"/>{bench?<><path d="M-47 3H47V15H-47Z" fill={color}/><path d="M-39 15V35M39 15V35" stroke="#687780" strokeWidth="7"/><circle cx="-15" cy="-2" r="17" fill="#26343d" stroke={color} strokeWidth="5"/><circle cx="12" cy="-4" r="11" fill="#172129" stroke={color} strokeWidth="4"/><path d="M32-17V3M26-17H38" stroke="#b7c5ca" strokeWidth="4"/></>:<><path d="M-44-30H30L45-19V29H-44Z" fill="#26343d" stroke="#657681" strokeWidth="1.5"/><path d="M30-30V18L45 29V-19Z" fill="#172129"/><path d="M-44 18H30L45 29H-44Z" fill={color} opacity=".7"/><rect x="-34" y="-20" width="47" height="32" rx={furnace?15:2} fill="#101920" stroke={color} strokeWidth="2"/>{furnace?<><path d="M-21 4Q-28-2-20-11Q-21-2-15-5Q-6-19-4-10Q5-1-2 6Z" fill={color} opacity={busy?1:.4}/><path d="M-14-30V-43H-1V-30" stroke="#657681" fill="#26343d"/></>:<><g className="gw-spindle"><circle cx="-10" cy="-4" r="11" fill="#738a96" stroke={color} strokeWidth="3"/><path d="M-20-4H0M-10-14V6" stroke="#172129" strokeWidth="4"/></g><path d="M-35 11H15" stroke="#9baeb6" strokeWidth="3"/></>}<rect x="19" y="-16" width="8" height="13" rx="1" fill={busy?'#88dec0':'#56757b'}/><circle cx="23" cy="6" r="2" fill="#e9b966"/><path d="M23-30V-40" stroke="#657681" strokeWidth="2"/><circle cx="23" cy="-41" r="3" fill={busy?'#7de0b8':'#56616a'}/></>}</g>;
}
export function ShopFloor({g,running,onBuy,onSelect}:{g:Career;running:boolean;onBuy:(bay:number)=>void;onSelect:(id:number)=>void}){
 const rows=g.floor+1,height=240+rows*180;
 const point=(location:string)=>{if(location==='supplier'||location==='stores')return{x:75,y:65};if(location==='vendor')return{x:500,y:65};if(location==='customer'||location==='dispatch')return{x:915,y:65};const m=g.equipment.find(e=>'m'+e.id===location);return m?{x:75+(m.bay%6)*168,y:205+Math.floor(m.bay/6)*180}:{x:75,y:65};};
 const cart=(m:Career['moves'][number])=>{const a=point(m.from),b=point(m.to),progress=Math.max(0,Math.min(1,(g.time-m.start)/(m.end-m.start))),mid=(a.y+b.y)/2,len=Math.abs(a.y-mid)+Math.abs(b.x-a.x)+Math.abs(b.y-mid);let d=progress*len,x=a.x,y=a.y;const first=Math.abs(a.y-mid);if(d<first)y=a.y+Math.sign(mid-a.y)*d;else{d-=first;y=mid;if(d<Math.abs(b.x-a.x))x=a.x+Math.sign(b.x-a.x)*d;else{x=b.x;d-=Math.abs(b.x-a.x);y=mid+Math.sign(b.y-mid)*d;}}return {a,b,x,y,mid};};
 return <section className="gw-floor"><div className="gw-section-heading"><div><span className="gw-eyebrow">YOUR MACHINE SHOP</span><h2>The shop floor <span>{g.equipment.length} / {bays(g)} bays</span></h2></div><div className="gw-floor-key"><span><i className={running?'gw-live':''}/>{running?'Shift running':'Time paused'}</span><span><i className="gw-amber"/>Material in transit</span></div></div><div className="gw-floor-scroll"><svg className={`gw-floor-svg ${running?'':'gw-still'}`} viewBox={`0 0 1000 ${height}`} aria-label="Shop floor showing installed machinery, empty bays, and material movement">
 <defs><pattern id="gw-grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#27343b" strokeWidth=".55"/></pattern><pattern id="gw-hatch" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="4" height="10" fill="#a38b4c" opacity=".25"/></pattern></defs>
 <rect width="1000" height={height} fill="url(#gw-grid)"/><rect x="12" y="114" width="976" height={height-139} fill="#18222966" stroke="#435059"/><path d={`M12 114H988M12 ${height-25}H988`} stroke="url(#gw-hatch)" strokeWidth="12"/>
 {[[75,'RECEIVING','Stock & purchases'],[290,'ENGINEERING',g.drawings.length+' controlled drawings'],[500,'OUTSIDE SERVICES',g.work.filter(w=>w.vendor).length+' / 4 batches active'],[710,'QUALITY',g.jobs.filter(j=>j.stage==='inspection').length+' lots awaiting release'],[915,'DISPATCH',g.delivered+' orders delivered']].map(([x,title,sub])=><g key={title}><rect x={Number(x)-72} y="23" width="144" height="70" rx="5" fill="#1a252d" stroke="#44535d"/><text x={Number(x)} y="49" textAnchor="middle" fill="#c7d3d8" fontSize="11" fontWeight="700" letterSpacing="1">{title}</text><text x={Number(x)} y="73" textAnchor="middle" fill="#8c9fa9" fontSize="11">{sub}</text></g>)}
 {Array.from({length:bays(g)},(_,bay)=>{const m=g.equipment.find(e=>e.bay===bay),x=75+(bay%6)*168,y=205+Math.floor(bay/6)*180,w=m&&g.work.find(w=>w.equipment===m.id),job=w&&g.jobs.find(j=>j.id===w.job),progress=w?Math.min(1,Math.max(0,(g.time-w.start)/(w.finish-w.start))):0;return <g key={bay} role="button" tabIndex={0} aria-label={m?`Inspect ${MACHINES[m.type].name} in bay ${bay+1}`:`Install equipment in bay ${bay+1}`} className="gw-bay" onClick={()=>m?onSelect(m.id):onBuy(bay)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();m?onSelect(m.id):onBuy(bay);}}}>
 <rect x={x-62} y={y-67} width="124" height="142" rx="4" fill={m?'#202c35':'#14202844'} stroke={w?'#76cbb1':m?'#53646f':'#42515a'} strokeDasharray={m?undefined:'5 5'}/><text x={x-51} y={y-51} fontSize="9" fill="#8b9ba5" letterSpacing="1.5">BAY {String(bay+1).padStart(2,'0')}</text>
 {m?<><g transform={`translate(${x},${y-6})`}><MachineArt type={m.type} color={MACHINES[m.type].color} busy={!!w&&g.time>=w.start}/></g><text x={x} y={y+45} textAnchor="middle" fill="#edf1ec" fontSize="12" fontWeight="600">{MACHINES[m.type].short}</text><text x={x} y={y+63} textAnchor="middle" fill={w?'#8ad7bd':'#98a9b4'} fontSize="10">{m.paused?'On hold':job?'WO-'+job.id+' · '+(g.time<w.start?'Cart arriving':hours(w!.finish-g.time)+' left'):'Available'}</text>{w&&<rect x={x-60} y={y+73} width={120*progress} height="3" fill="#82d5b7"/>}</>:<><path d={`M${x-10} ${y}H${x+10}M${x} ${y-10}V${y+10}`} stroke="#607985" strokeWidth="2"/><text x={x} y={y+38} textAnchor="middle" fill="#96a9b5" fontSize="11">Install equipment</text></>}
 </g>;})}
 {g.moves.filter(m=>m.kind!=='purchase'||m.start+1.65<g.time).slice(0,40).map(m=>{const {a,b,x,y,mid}=cart(m);return <g key={m.id} pointerEvents="none"><path d={`M${a.x},${a.y}V${mid}H${b.x}V${b.y}`} fill="none" stroke={ITEMS[m.item].color} strokeWidth="1.5" opacity=".35" strokeDasharray="4 5"/><rect x={x-5} y={y-5} width="10" height="10" rx="2" fill={ITEMS[m.item].color} stroke="#142029" strokeWidth="2"/><title>{m.qty} {ITEMS[m.item].short} · {m.from} to {m.to}</title></g>;})}
 <text x="24" y={height-7} fontSize="10" fill="#869aa5" letterSpacing="2">{g.floor===0?'UNIT 01':`UNITS 01–0${g.floor+1}`} · {bays(g)*144} SQ FT PRODUCTION FLOOR</text></svg></div><div className="gw-floor-caption"><span><Package size={14}/> Parts stay with their work order as they travel through the shop.</span><span><Truck size={14}/> Longer moves take more cart time.</span></div></section>;
}
export function EquipmentMarket({g,act,bay,onClose}:{g:Career;act:Act;bay:number|null;onClose:()=>void}){const [used,setUsed]=useState(true);return <Modal open={bay!==null} onClose={onClose} title={`Equip bay ${(bay??0)+1}`} description="Equipment stays with your company. Machines need an operator; the owner can cover one job at a time." wide><div className="gw-switch-row"><label htmlFor="gw-used">Used equipment <small>68% of new price · 80% of new cycle speed</small></label><Switch id="gw-used" checked={used} onCheckedChange={setUsed}/></div><div className="gw-machine-market">{MACHINE_IDS.filter(id=>!vendor(id)).map(id=><article key={id}><div className="gw-machine-picture"><svg viewBox="-65 -60 130 115" aria-hidden="true"><MachineArt type={id} color={MACHINES[id].color} busy={false}/></svg></div><div><h3>{MACHINES[id].name}</h3><p>{MACHINES[id].detail}</p><button className="gw-primary" disabled={g.cash<machinePrice(id,used)} onClick={()=>{if(bay!==null&&act({type:'buyMachine',machine:id,used,bay}))onClose();}}><Plus size={14}/>Install · {money(machinePrice(id,used))}</button></div></article>)}</div></Modal>;}
export function MachineDetails({g,m,act,onClose}:{g:Career;m:Equipment|undefined;act:Act;onClose:()=>void}){const [moving,setMoving]=useState('');if(!m)return null;const w=g.work.find(w=>w.equipment===m.id),j=w&&g.jobs.find(j=>j.id===w.job),worker=w&&(w.worker===0?'You, the owner':g.people.find(p=>p.id===w.worker)?.name);return <Modal open={!!m} onClose={onClose} title={MACHINES[m.type].name} description={`Bay ${m.bay+1} · ${m.used?'Used':'New'} · Installed for ${money(m.paid)}`}><p>{MACHINES[m.type].detail}</p><div className="gw-metrics three"><div><small>Cycle speed</small><strong>{Math.round((m.used?.8:1)*(1+m.level*.25)*100)}%</strong></div><div><small>Operations done</small><strong>{m.completed}</strong></div><div><small>Hours working</small><strong>{m.busy.toFixed(1)}</strong></div></div>{w&&j?<div className="gw-note"><strong>{j.name}</strong><p>{RECIPES[j.tasks[w.task].recipe].name} · {worker}</p><Bar value={(g.time-w.start)/(w.finish-w.start)*100} label="Cycle progress"/><small>{hours(w.finish-g.time)} remaining, including any material transfer.</small></div>:<p className="gw-note">{m.paused?'Machine is held. Resume it to take more work.':'Ready for a released job and an available operator.'}</p>}<div className="gw-button-row"><button className="gw-secondary" onClick={()=>act({type:'pauseMachine',id:m.id})}>{m.paused?'Resume machine':'Hold after current cycle'}</button><button className="gw-primary" disabled={m.level>=2||g.cash<Math.ceil(machinePrice(m.type)*.3)} onClick={()=>act({type:'upgradeMachine',id:m.id})}><Settings2 size={14}/>{m.level>=2?'Fully tooled':`Tooling +25% · ${money(Math.ceil(machinePrice(m.type)*.3))}`}</button></div><div className="gw-form-row"><Choice label="Move to empty bay" value={moving} options={Array.from({length:bays(g)},(_,i)=>i).filter(i=>!g.equipment.some(e=>e.bay===i)).map(i=>({value:String(i),label:'Bay '+(i+1)}))} disabled={!!w} onChange={setMoving}/><button className="gw-secondary" disabled={!!w||moving===''||g.cash<250} onClick={()=>{if(act({type:'moveMachine',id:m.id,bay:Number(moving)}))setMoving('');}}>Move · $250</button></div><button className="gw-danger" disabled={!!w} onClick={()=>{if(act({type:'sellMachine',id:m.id}))onClose();}}>Sell equipment · recover {money(Math.floor(m.paid*.6))}</button></Modal>;}
