'use client';
import {useEffect,useId,useState,type ReactNode} from 'react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Progress} from '@/components/ui/progress';
import {ITEMS,PLANS,RECIPES,MACHINES,neededEquipment,materialCost,processCost,PRICE,type Career,type CareerAction} from '@/lib/career';
export type Act=(action:CareerAction)=>boolean;
export const money=(n:number)=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
export const hours=(n:number)=>`${Math.max(0,n).toFixed(1)}h`;
export function Choice({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;disabled?:boolean}){const id=useId();return <div className="gw-field"><label id={id}>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-labelledby={id}><SelectValue/></SelectTrigger><SelectContent className="gw-select">{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
export function NumberField({label,value,min=1,max=100,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(n:number)=>void}){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);const commit=()=>{const n=Number(draft);if(draft!==''&&Number.isInteger(n)&&n>=min&&n<=max)onChange(n);else setDraft(String(value));};return <label className="gw-field"><span>{label}</span><Input type="number" min={min} max={max} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description:string;children:ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className={`gw-modal ${wide?'gw-wide':''}`}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>;}
export function Bar({value,label}:{value:number;label:string}){return <Progress className="gw-progress" value={Math.max(0,Math.min(100,value))} aria-label={label}/>;}
export function Empty({title,children}:{title:string;children:ReactNode}){return <div className="gw-empty"><h3>{title}</h3><p>{children}</p></div>;}
export function Route({g,plan,qty,estimate=true}:{g:Career;plan:string;qty:number;estimate?:boolean}){const p=PLANS[plan],missing=neededEquipment(g,plan);return <div className="gw-route"><ol>{p.steps.map(([id,n],i)=>{const r=RECIPES[id];return <li key={id}><span className="gw-step-number">{i+1}</span><div><strong>{r.name}</strong><small>{n*qty} operations · {MACHINES[r.machine].short} · {money(r.fee*PRICE)} / unit</small></div><span className="gw-item-dot" style={{background:ITEMS[r.output].color}}/></li>;})}</ol>{missing.length>0?<p className="gw-warning">Equipment needed: {missing.map(m=>MACHINES[m].short).join(', ')}.</p>:<p className="gw-positive">Your shop and available vendors can run this route.</p>}{estimate&&<div className="gw-estimate"><span>Materials <strong>{money(materialCost(plan,qty))}</strong></span><span>Process fees <strong>{money(processCost(plan,qty))}</strong></span><small>Plus handling, setups, labor, and shop overhead.</small></div>}</div>;}
