'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Cog,Play,Pause,FastForward,Plus,ArrowRight,Factory,Users,BriefcaseBusiness,FilePenLine,Package,Landmark,HelpCircle,Save,AlertTriangle,Building2,Check,Clock3} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {advanceCareer,careerAction,isCareerAction,runningJobs,dailyOverhead,bays,clock,day,jobBlocker,ITEMS,MACHINES,type CareerAction,type Offer,type OwnerRole} from '@/lib/career';
import {useCareer} from './use-career';
import {ShopFloor,EquipmentMarket,MachineDetails} from './career-floor';
import {Orders,Quote,JobDetails,DispatchSetting} from './career-orders';
import {People,Engineering,Stock,Accounts,ownerOptions} from './career-company';
import {Choice,Modal,Empty,money} from './career-ui';
import './career.css';
type ContextAPI={registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
const tabList=[{id:'floor',name:'Shop floor',icon:Factory},{id:'orders',name:'Orders',icon:BriefcaseBusiness},{id:'people',name:'People',icon:Users},{id:'engineering',name:'Engineering',icon:FilePenLine},{id:'stock',name:'Stock',icon:Package},{id:'accounts',name:'Accounts',icon:Landmark}];
export default function CareerPage(){
 const {data:g,ref,change,loaded,error,saveError,status,conflict,save,load}=useCareer();
 const [tab,setTab]=useState('floor'),[running,setRunning]=useState(false),[speed,setSpeed]=useState(1),[market,setMarket]=useState<number|null>(null),[machine,setMachine]=useState<number|null>(null),[offer,setOffer]=useState<Offer|null>(null),[job,setJob]=useState<number|null>(null),[guide,setGuide]=useState(false),[notice,setNotice]=useState('');
 const act=useCallback((action:CareerAction)=>{let success=false;change(current=>{const r=careerAction(current,action);success=r.ok;if(r.message)setNotice(r.message);return r.ok?r.state:current;});return success;},[change]);
 const advance=useCallback((hours:number)=>{setRunning(false);change(current=>advanceCareer(current,hours));},[change]);
 const handlers=useRef({act,advance});useEffect(()=>{handlers.current={act,advance};},[act,advance]);
 useEffect(()=>{if(!running||!loaded||conflict)return;const interval=setInterval(()=>{if(!document.hidden)change(current=>advanceCareer(current,.05*speed));},250);return()=>clearInterval(interval);},[running,loaded,conflict,speed,change]);
 useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(timeout);},[notice]);
 useEffect(()=>{const context=(document as Document&{modelContext?:ContextAPI}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:Parameters<ContextAPI['registerTool']>[0])=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
 register({name:'read_machine_shop',title:'Inspect machine-shop company',description:'Read permanent company finances, equipment, staff, inquiries, work orders, physical work in progress, inventory, and retained drawings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>ref.current});
 register({name:'manage_machine_shop',title:'Make a machine-shop business decision',description:'Perform one validated game action, using the same business rules as the buttons: buyMachine, hire, accept, release, supplyJob, facility, stockLot, owner, and other career actions. All effects are in-game only.',inputSchema:{type:'object',properties:{action:{type:'object'}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const a=(input as {action?:unknown})?.action;if(!isCareerAction(a))return{ok:false,error:'Invalid action.'};const ok=handlers.current.act(a);return{ok,state:ref.current};}});
 register({name:'advance_machine_shop',title:'Advance the working day',description:'Advance between 0.05 and 8 simulated working hours. Jobs, payroll, rent, and deliveries progress in the permanent company. Pauses live playback.',inputSchema:{type:'object',properties:{hours:{type:'number',minimum:.05,maximum:8}},required:['hours'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const h=(input as {hours?:unknown})?.hours;if(typeof h!=='number'||!Number.isFinite(h)||h<.05||h>8)return{error:'Hours must be between 0.05 and 8.'};handlers.current.advance(h);return ref.current;}});return()=>lifecycle.abort();},[ref]);
 const jobs=runningJobs(g),selectedJob=g.jobs.find(j=>j.id===job),selectedMachine=g.equipment.find(m=>m.id===machine),idleStart=!g.equipment.length&&!g.people.length&&!g.jobs.length&&g.time<8;
 const buy=()=>{const bay=Array.from({length:bays(g)},(_,i)=>i).find(i=>!g.equipment.some(m=>m.bay===i));if(bay!==undefined)setMarket(bay);else setNotice('All bays are occupied. Expand the shop to install more machinery.');};
 const created=()=>{setTab('orders');const j=[...ref.current.jobs].filter(j=>j.stage==='planning').sort((a,b)=>b.id-a.id)[0];if(j)setJob(j.id);};
 return <main className="gw-app"><header className="gw-header"><a className="gw-brand" href="/"><span className="gw-brand-symbol"><Cog size={27}/></span><span>GEAR WORKS<small>A MACHINE-SHOP BUSINESS</small></span></a><div className="gw-header-right"><span className="gw-save-status"><Save size={13}/>{status}</span><button className="gw-icon-button" onClick={()=>setGuide(true)} aria-label="How to run your shop"><HelpCircle size={19}/></button></div></header>
 {!loaded?<section className="gw-loading"><Cog size={34}/><h1>{error?'Could not open your company':'Opening your company…'}</h1>{error&&<><p>{error}</p><button className="gw-primary" onClick={()=>void load()}>Try again</button></>}</section>:<>
 <section className="gw-company-header"><div><span className="gw-eyebrow">EST. DAY 1 · {g.people.length?g.people.length+' EMPLOYEES':'OWNER OPERATED'}</span><h1>{g.name}</h1><p>{g.reputation>=28?'Gear and gearbox manufacturer':g.reputation>=12?'An established job shop':g.delivered?'Building a name, one good job at a time.':'Your company. Your equipment. Your way of working.'}</p></div><div className="gw-top-stats"><div><small>Cash on hand</small><strong>{money(g.cash)}</strong></div><div><small>Daily overhead</small><strong>{money(dailyOverhead(g))}</strong></div><div><small>Reputation</small><strong>{g.reputation}<em>/100</em></strong></div></div></section>
 {(conflict||saveError)&&<div className="gw-error" role="alert"><AlertTriangle size={18}/><span>{conflict?'This company changed in another tab. Reload before continuing.':saveError}</span><button className="gw-secondary" onClick={()=>{setRunning(false);if(conflict)window.location.reload();else void save();}}>{conflict?'Reload company':'Retry save'}</button></div>}
 {g.arrears>0&&<div className="gw-error"><AlertTriangle size={18}/><span>{money(g.arrears)} in overdue operating bills. Staff are waiting for payroll.</span><button className="gw-text" onClick={()=>setTab('accounts')}>Open accounts <ArrowRight size={15}/></button></div>}
 <section className="gw-timebar"><div className="gw-clock"><Clock3 size={18}/><strong>{clock(g.time)}</strong><span>{running&&!conflict?'Working':'Paused'}</span></div><div className="gw-time-controls"><div className="gw-speeds" aria-label="Simulation speed">{[1,4,12].map(n=><button key={n} aria-pressed={speed===n} onClick={()=>setSpeed(n)}>{n}×</button>)}</div><button className="gw-primary" disabled={conflict} onClick={()=>setRunning(v=>!v)}>{running?<Pause size={15}/>:<Play size={15}/>} {running?'Pause':'Run shop'}</button><button className="gw-secondary" disabled={conflict} onClick={()=>advance(1)}>+1 hour</button><button className="gw-secondary" disabled={conflict} onClick={()=>advance(8)}><FastForward size={15}/>Work one day</button></div></section>
 <Tabs value={tab} onValueChange={setTab} className="gw-tabs"><TabsList className="gw-tab-list">{tabList.map(t=><TabsTrigger key={t.id} value={t.id}><t.icon size={16}/>{t.name}{t.id==='orders'&&jobs.length>0&&<span>{jobs.length}</span>}</TabsTrigger>)}</TabsList>
 <TabsContent value="floor" className="gw-tab-content">
 {idleStart&&<section className="gw-start"><div><span className="gw-eyebrow">THE KEYS ARE YOURS</span><h2>$25,000. An empty floor.<br/>A business to build.</h2><p>Start cutting gears, assemble bought-in components, or sell engineering expertise. Keep the cash, equipment, people, and knowledge you earn.</p><div className="gw-button-row"><button className="gw-primary" onClick={buy}><Plus size={16}/>Buy your first machine</button><button className="gw-secondary" onClick={()=>setTab('orders')}>See available work <ArrowRight size={16}/></button></div></div><div className="gw-start-note"><span>YOUR STARTING ASSETS</span><strong>6 empty bays</strong><p>Basic inspection bench<br/>A network of outside services<br/>Your own time and skill</p><button className="gw-text" onClick={()=>setTab('engineering')}>Start with engineering instead <ArrowRight size={15}/></button></div></section>}
 <ShopFloor g={g} running={running&&!conflict} onBuy={setMarket} onSelect={setMachine}/>
 <div className="gw-floor-actions"><div className="gw-button-row"><button className="gw-primary" onClick={buy}><Plus size={16}/>Add equipment</button><button className="gw-secondary" onClick={()=>setTab('people')}><Users size={16}/>Hire people</button><button className="gw-secondary" onClick={()=>setTab('orders')}><BriefcaseBusiness size={16}/>Find work</button></div><button className="gw-secondary" disabled={g.floor>=2||g.cash<15000*(g.floor+1)} onClick={()=>act({type:'facility',facility:'floor'})}><Building2 size={16}/>{g.floor>=2?'All 18 bays leased':`Expand +6 bays · ${money(15000*(g.floor+1))}`}</button></div>
 <div className="gw-floor-bottom"><section className="gw-card"><div className="gw-section-heading"><h3>What is happening in the shop</h3><button className="gw-text" onClick={()=>setTab('orders')}>Order book <ArrowRight size={14}/></button></div>{jobs.length?<div className="gw-live-jobs">{jobs.map(j=><button key={j.id} onClick={()=>setJob(j.id)}><span className={`gw-stage ${j.stage}`}>{j.paused?'Held':j.stage}</span><div><strong>{j.name}</strong><small>{jobBlocker(g,j)}</small></div><ArrowRight size={15}/></button>)}</div>:<Empty title="The floor is quiet">Take on a customer order or make a lot of your own products. Release the work and run the shop to get things moving.</Empty>}</section><section className="gw-card"><h3>How you run the shop</h3><Choice label="Your role today" value={g.owner} options={ownerOptions} onChange={role=>act({type:'owner',role:role as OwnerRole})}/><DispatchSetting g={g} act={act}/><div className="gw-owned-assets"><span><strong>{g.equipment.length}</strong> machines</span><span><strong>{g.people.length}</strong> employees</span><span><strong>{g.drawings.length}</strong> drawings</span><span><strong>{g.delivered}</strong> deliveries</span></div><small className="gw-muted">Expansion adds $140 in daily rent per six bays. All assets and work in progress save with your company.</small></section></div>
 </TabsContent><TabsContent value="orders" className="gw-tab-content"><Orders g={g} onOffer={setOffer} onJob={j=>setJob(j.id)}/></TabsContent><TabsContent value="people" className="gw-tab-content"><People g={g} act={act}/></TabsContent><TabsContent value="engineering" className="gw-tab-content"><Engineering g={g} act={act}/></TabsContent><TabsContent value="stock" className="gw-tab-content"><Stock g={g} act={act} onCreated={created}/></TabsContent><TabsContent value="accounts" className="gw-tab-content"><Accounts g={g} act={act}/></TabsContent></Tabs>
 <footer className="gw-footer"><span>One lasting company · Progress saves automatically · Time stops while you are away</span><details><summary>Earlier versions</summary><a href="/idle">Previous idle shop</a><a href="/design">Production puzzles</a><a href="/classic">Original factory</a></details></footer>
 </>}
 {notice&&<div className="gw-toast" role="status"><Check size={16}/><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Dismiss notification">×</button></div>}
 <EquipmentMarket g={g} act={act} bay={market} onClose={()=>setMarket(null)}/><MachineDetails g={g} m={selectedMachine} act={act} onClose={()=>setMachine(null)}/>{offer&&<Quote key={offer.id} g={g} offer={offer} act={act} onClose={()=>setOffer(null)} onAccepted={created}/>} {selectedJob&&<JobDetails g={g} j={selectedJob} act={act} onClose={()=>setJob(null)} onEquipment={()=>{setJob(null);buy();}}/>}
 <Modal open={guide} onClose={()=>setGuide(false)} title="Build a company that lasts" description="Your cash, equipment, people, drawings, inventory, and unfinished jobs carry forward together."><div className="gw-stack"><p><strong>Choose your business.</strong> Used hobbing equipment makes a small gear shop affordable. An assembly bench lets you build reducers from bought-in parts. CAD and metrology let you sell design and sample-recovery services.</p><p><strong>Plan the work.</strong> Prepare a quote at the sales desk. Decide what to buy, make, or subcontract, choose the lead time, and collect a deposit. Reserve material and release the order.</p><p><strong>Manage shared capacity.</strong> Jobs compete for your staff and machinery. The owner can cover any department, one task at a time. Priorities, dedicated operators, outside batch sizes, and equipment placement change the flow.</p><p><strong>Build beyond orders.</strong> House production lots let you make and sell your own gear sets and gearboxes. Keep inventory, improve tooling, hire specialists, and expand the floor.</p><p><strong>Watch the cash.</strong> Wages, rent, and interest come due every working day. Customer balances arrive after inspection and delivery. An account line can bridge a shortage; late jobs reduce payment and reputation.</p><p><strong>Keep what you learn.</strong> Drawings and repeat setups stay with the business. Customers return, lot sizes increase, and stronger reputation brings more demanding work.</p><p className="gw-note">Run, pause, or advance a working day whenever you like. There are no isolated rounds or end-of-job resets. Equipment prices and working times are simplified game values.</p></div></Modal>
 </main>;
}
