'use client';
import {useEffect,useState} from 'react';
import {Star,Check,LockKeyhole,Lightbulb,Settings2,Target,Clock3,Wallet} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Input} from '@/components/ui/input';
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from '@/components/ui/table';
import {CASH} from '@/lib/shop';
import {CHALLENGES,MISSIONS,FREEPLAY,ITEMS,RECIPES,MACHINES,unlocked,cellName,inputCount,outputItem,challengeFor,type Blueprint,type Challenge,type DesignSave,type Run,type Result,type Cell} from '@/lib/process';
export function NumberField({label,value,min=1,max=100,disabled=false,onChange}:{label:string;value:number;min?:number;max?:number;disabled?:boolean;onChange:(n:number)=>void}){
 const[draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);const commit=()=>{const n=Number(draft);if(draft!==''&&Number.isInteger(n)&&n>=min&&n<=max){if(n!==value)onChange(n);}else setDraft(String(value));};
 return <label className="pd-number"><span>{label}</span><Input type="number" value={draft} min={min} max={max} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
export function Choice({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;disabled?:boolean}){return <div className="pd-choice"><label>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>;}
export function Stars({n}:{n:number}){return <span className="pd-stars" aria-label={`${n} of 3 stars`}>{[1,2,3].map(i=><Star size={17} key={i} fill={i<=n?'currentColor':'none'} className={i<=n?'earned':''}/>)}</span>;}
export function Contracts({open,setOpen,save,onSelect}:{open:boolean;setOpen:(v:boolean)=>void;save:DesignSave;onSelect:(id:string)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="pd-dialog pd-contract-dialog"><DialogHeader><DialogTitle>Production contracts</DialogTitle><DialogDescription>Deliver the order to unlock the next job. Replay a contract to improve time and cost.</DialogDescription></DialogHeader><div className="pd-contract-list">{MISSIONS.map((c,i)=>{const available=unlocked(save,i),best=save.best[c.id];return <button key={c.id} disabled={!available} aria-pressed={save.mission===c.id} onClick={()=>{onSelect(c.id);setOpen(false);}}><div className="pd-contract-number">{available?i===CHALLENGES.length?<Settings2 size={20}/>:String(i+1).padStart(2,'0'):<LockKeyhole size={18}/>}</div><div><strong>{c.name}</strong><span>{c.focus}</span><small>{c.goals.map(g=>`${g.qty} ${ITEMS[g.item].short.toLowerCase()}`).join(' + ')}</small></div><Stars n={best?.stars||0}/></button>;})}</div></DialogContent></Dialog>;}
export function Guide({open,setOpen}:{open:boolean;setOpen:(v:boolean)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="pd-dialog"><DialogHeader><DialogTitle>Design. Test. Improve.</DialogTitle><DialogDescription>Each contract starts with a fresh equipment allowance and an operating budget.</DialogDescription></DialogHeader><div className="pd-guide"><p><strong>1. Lay out the process.</strong> Choose a machine or supplier above the floor, then select an empty bay. Drag cells to move them, or use Move cell.</p><p><strong>2. Connect material routes.</strong> Select a cell, choose Connect output, and select the destination. Every material must have a route. Assembly needs a separate stream for each input.</p><p><strong>3. Set the flow.</strong> Pick recipes, source lot quantities, buffer sizes, and route carts. Branches take turns and skip full destinations. Route lot limits reserve the right quantities for each branch.</p><p><strong>4. Test a shift.</strong> Run, pause, speed up, or finish the simulation instantly. Cells show whether they are working, starved, or blocked. Tests use fresh stock every time.</p><p><strong>5. Meet the contract.</strong> Deliver the order before time or operating funds run out. Earn extra stars for speed and running cost. Edits refund equipment immediately; no waiting for money.</p><p className="pd-guide-note">Each grid step is 12 ft. Longer links tie up carts longer; each cart carries one inventory unit. Each machine’s input capacity applies separately to every material. One gear set contains a matched pinion and wheel. Simulated time advances only during your test.</p></div></DialogContent></Dialog>;}
export function ProductionGraph({history,target}:{history:Run['history'];target:number}){const w=700,h=110,maxT=Math.max(1,...history.map(p=>p.time)),maxY=Math.max(target,...history.map(p=>p.delivered),1),points=history.map(p=>`${12+p.time/maxT*(w-24)},${h-12-p.delivered/maxY*(h-28)}`).join(' '),goalY=h-12-target/maxY*(h-28);return <svg className="pd-production-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Production: ${history.at(-1)?.delivered||0} delivered against a target of ${target}`}><line x1="12" x2={w-12} y1={goalY} y2={goalY} stroke="#718aa0" strokeDasharray="5 5"/><polyline points={points} fill="none" stroke="#81dcc5" strokeWidth="3"/><text x={w-12} y={goalY+14} fill="#a8bbc9" fontSize="12" textAnchor="end">Target {target}</text><text x="12" y={h-1} fill="#849aaa" fontSize="11">0s</text><text x={w-12} y={h-1} fill="#849aaa" fontSize="11" textAnchor="end">{maxT.toFixed(0)}s</text></svg>;}
export function RunReport({run,result,b,c,onCell,onEdit,onNext}:{run:Run|null;result:Result|null;b:Blueprint;c:Challenge;onCell:(id:number)=>void;onEdit:()=>void;onNext:()=>void}){
 if(!run&&result){b=result.blueprint;c=challengeFor(c.id,b);}
 const states=run?.states||result?.states;if(!states)return null;const time=run?.time||result?.time||1,delivered=run?.delivered||result?.delivered||{},finished=run?.finished||!run,success=run?.success??result?.success;const cells=b.cells.filter(n=>n.kind==='machine'&&states[n.id]);const bottleneck=[...cells].sort((a,z)=>states[z.id].busy-states[a.id].busy)[0],blocked=[...cells].sort((a,z)=>states[z.id].blocked-states[a.id].blocked)[0];
 return <section className="pd-report"><div className="pd-report-heading"><div><span className="pd-eyebrow">{finished?'SHIFT REVIEW':'LIVE PROCESS ANALYSIS'}</span><h2>{finished?(success?'Contract delivered.':'The design needs another pass.'):'Where is the work waiting?'}</h2></div>{finished&&result&&<Stars n={result.stars}/>}</div>
 <div className="pd-review-stats"><div><span>Elapsed</span><strong>{time.toFixed(1)}s <small>/ {c.duration}s</small></strong></div><div><span>Operating cost</span><strong>{CASH(run?.spent??result?.cost??0)} <small>/ {CASH(c.operating)}</small></strong></div><div><span>Delivered</span><strong>{c.goals.map(g=>`${delivered[g.item]||0}/${g.qty}`).join(' + ')}</strong></div><div><span>Most occupied cell</span><strong>{bottleneck?`${MACHINES[bottleneck.machine].short} #${bottleneck.id}`:'—'}</strong></div></div>
 <ProductionGraph history={run?.history||result?.history||[]} target={c.goals.reduce((n,g)=>n+g.qty,0)}/>
 <div className="pd-findings">{bottleneck&&<p><strong>{cellName(bottleneck)} #{bottleneck.id}</strong> worked for {Math.round(states[bottleneck.id].busy/time*100)}% of the shift. {states[bottleneck.id].busy/time>.7?'Try a cycle upgrade or a parallel cell if you need more throughput.':'Check startup delays and incoming supply before adding more equipment.'}</p>}{blocked&&states[blocked.id].blocked>3&&<p><strong>{cellName(blocked)} #{blocked.id}</strong> spent {states[blocked.id].blocked.toFixed(1)}s blocked. Inspect its outgoing route, carts, and destination capacity.</p>}{cells.some(n=>states[n.id].unfunded>1)&&<p><strong>Operating funds ran out.</strong> Reduce supplier lot quantities, change sourcing, or use cheaper processes.</p>}</div>
 <div className="pd-stat-table"><Table><TableHeader><TableRow><TableHead>Work cell</TableHead><TableHead>Working</TableHead><TableHead>Input starved</TableHead><TableHead>Output blocked</TableHead><TableHead>Completed</TableHead></TableRow></TableHeader><TableBody>{cells.map(n=>{const s=states[n.id];return <TableRow key={n.id}><TableCell><button onClick={()=>onCell(n.id)}>{cellName(n)} <small>#{n.id}</small></button></TableCell><TableCell><span className="pd-util-bar"><i style={{width:`${Math.min(100,s.busy/time*100)}%`}}/></span>{Math.round(s.busy/time*100)}%</TableCell><TableCell>{s.starved.toFixed(1)}s</TableCell><TableCell>{s.blocked.toFixed(1)}s</TableCell><TableCell>{s.produced}</TableCell></TableRow>;})}</TableBody></Table></div>
 {finished&&<div className="pd-report-actions"><button className="pd-primary" onClick={onEdit}>Revise this design</button>{success&&c.id!==FREEPLAY.id&&<button className="pd-secondary" onClick={onNext}>Next contract</button>}<span>One star for delivery · one by {c.parTime}s · one at {CASH(c.parCost)} running cost</span></div>}</section>;
}
