'use client';
import {Link2,Move,Copy,Trash2,Package,Info} from 'lucide-react';
import {CASH} from '@/lib/shop';
import {Choice,NumberField} from './process-panels';
import {ITEMS,ITEM_IDS,MACHINES,RECIPES,outputItem,cellName,cellCost,cycle,travelTime,recipesFor,inputCount,type Blueprint,type Challenge,type Cell,type Link,type Run,type ItemId} from '@/lib/process';
export function ProcessInspector({b,c,run,cell,link,editable,onCellChange,onLinkChange,onConnect,onMove,onCopy,onDelete,onDeleteLink,onSelectCell,onSelectLink}:{b:Blueprint;c:Challenge;run:Run|null;cell:Cell|undefined;link:Link|undefined;editable:boolean;onCellChange:(patch:Partial<Cell>)=>void;onLinkChange:(patch:Partial<Link>)=>void;onConnect:()=>void;onMove:()=>void;onCopy:()=>void;onDelete:()=>void;onDeleteLink:()=>void;onSelectCell:(id:number)=>void;onSelectLink:(id:number)=>void}){
 if(link){const from=b.cells.find(n=>n.id===link.from)!,to=b.cells.find(n=>n.id===link.to)!,duration=travelTime(b,link);return <aside className="pd-inspector"><span className="pd-eyebrow">MATERIAL ROUTE #{link.id}</span><h2>{ITEMS[link.item].short}</h2><div className="pd-route-endpoints"><button onClick={()=>onSelectCell(from.id)}>{cellName(from)} <small>#{from.id}</small></button><span>to</span><button onClick={()=>onSelectCell(to.id)}>{cellName(to)} <small>#{to.id}</small></button></div><div className="pd-specs"><div><span>Travel distance</span><strong>{(Math.abs(from.x-to.x)+Math.abs(from.y-to.y))*12} ft</strong></div><div><span>Transfer time</span><strong>{duration}s</strong></div><div><span>Route capacity</span><strong>{(60*link.carts/duration).toFixed(1)} units/min</strong></div><div><span>Investment</span><strong>{CASH(35+(link.carts-1)*100)}</strong></div></div><Choice label="Dedicated carts" value={String(link.carts)} options={[1,2,3].map(n=>({value:String(n),label:`${n} cart${n>1?'s':''}${n>1?` · +${CASH((n-1)*100)}`:''}`}))} disabled={!editable} onChange={v=>onLinkChange({carts:Number(v)})}/><NumberField label="Lot limit · 0 = unlimited" value={link.limit} min={0} disabled={!editable} onChange={limit=>onLinkChange({limit})}/><p className="pd-help">A lot limit caps transfers on this route during one test. Use it to allocate material between branches.</p>{run&&<div className="pd-inventory"><h3>Route in this test</h3><p>{run.routed[link.id]||0} sent · {run.shipments.filter(m=>m.link===link.id).length} in transit</p></div>}<button className="pd-delete" disabled={!editable} onClick={onDeleteLink}><Trash2 size={15}/>Remove route</button></aside>;}
 if(!cell)return <aside className="pd-inspector pd-inspector-empty"><span className="pd-eyebrow">DESIGN WORKBENCH</span><h2>Build the material flow.</h2><p>Choose equipment above the floor and place it in an empty bay. Select a cell to set its recipe and connections.</p><div className="pd-step"><span>1</span><div><strong>Place the operation</strong><small>Every machine runs one recipe. Add parallel cells when you need capacity.</small></div></div><div className="pd-step"><span>2</span><div><strong>Connect the parts</strong><small>Use the link button on a cell, then select a compatible destination.</small></div></div><div className="pd-step"><span>3</span><div><strong>Run the test</strong><small>Watch buffers, transport, and machine time. Revise with a fresh allowance.</small></div></div></aside>;
 const state=run?.states[cell.id],output=outputItem(cell),recipe=RECIPES[cell.recipe];
 return <aside className="pd-inspector"><span className="pd-eyebrow">{cell.kind==='machine'?'WORK CELL':cell.kind==='source'?'PURCHASED MATERIAL':cell.kind==='sink'?'CUSTOMER DISPATCH':'INTERMEDIATE STORAGE'} #{cell.id}</span><h2>{cellName(cell)}</h2>{cell.kind==='machine'?<><Choice label="Operation" value={cell.recipe} disabled={!editable} onChange={recipe=>onCellChange({recipe})} options={recipesFor(c,cell.machine).map(([id,r])=>({value:id,label:r.name}))}/><p className="pd-help">{recipe.note}</p><div className="pd-bom"><h3>Each cycle consumes</h3>{Object.entries(recipe.input).map(([item,n])=><div key={item}><i style={{background:ITEMS[item as ItemId].color}}/><span>{n} × {ITEMS[item as ItemId].short}</span></div>)}<h3>Produces</h3><div><i style={{background:ITEMS[output].color}}/><span>1 × {ITEMS[output].short}</span></div></div><div className="pd-specs"><div><span>Cycle time</span><strong>{cycle(cell).toFixed(1)}s</strong></div><div><span>Process fee</span><strong>{CASH(recipe.fee)} / cycle</strong></div><div><span>Equipment + setup</span><strong>{CASH(cellCost(cell))}</strong></div></div><Choice label="Tooling / service level" value={String(cell.level)} disabled={!editable} options={[0,1,2].map(n=>({value:String(n),label:`${(1+n*.3).toFixed(1)}× speed${n?` · +${CASH(Math.round(MACHINES[cell.machine].cost*.4*n))}`:' · standard'}`}))} onChange={v=>onCellChange({level:Number(v)})}/></>:<><Choice label={cell.kind==='source'?'Purchase material':cell.kind==='sink'?'Accept product':'Buffer material'} value={cell.item} disabled={!editable} options={(cell.kind==='source'?c.sources:cell.kind==='sink'?c.goals.map(g=>g.item):ITEM_IDS).map(i=>({value:i,label:ITEMS[i].name}))} onChange={v=>onCellChange({item:v as ItemId})}/><p className="pd-help">{ITEMS[cell.item].detail}</p>{cell.kind==='source'&&<><NumberField label="Purchase lot quantity" value={cell.lot} disabled={!editable} onChange={lot=>onCellChange({lot})}/><Choice label="Delivery interval" value={String(cell.interval)} disabled={!editable} options={[2,4,8].map(n=>({value:String(n),label:`One unit every ${n} seconds`}))} onChange={v=>onCellChange({interval:Number(v)})}/><div className="pd-specs"><div><span>Unit price</span><strong>{CASH(ITEMS[cell.item].buy)}</strong></div><div><span>Maximum lot cost</span><strong>{CASH(cell.lot*ITEMS[cell.item].buy)}</strong></div></div><p className="pd-help">Purchases draw from the operating allowance as units arrive. Supply pauses when its rack is full.</p></>}{cell.kind==='sink'&&<p className="pd-help">Arriving product counts toward the contract. Dispatch cells do not supply other operations.</p>}</>}
 {cell.kind!=='sink'&&<Choice label={cell.kind==='machine'?'Buffer slots · per input and output':'Rack capacity'} value={String(cell.capacity)} disabled={!editable} options={[3,6,9,12].map(n=>({value:String(n),label:`${n} units${cell.kind==='machine'?' per material':''}${n>3&&cell.kind!=='source'?` · +${CASH((n-3)*20)}`:''}`}))} onChange={v=>onCellChange({capacity:Number(v)})}/>}
 {state&&<div className="pd-inventory"><h3>Material at this cell</h3>{Object.entries(state.input).map(([i,n])=><div key={i}><span>{ITEMS[i as ItemId].short}</span><strong>{n}</strong></div>)}<div><span>{cell.kind==='sink'?'Delivered':'Output on rack'}</span><strong>{cell.kind==='sink'?state.received:state.output}</strong></div>{state.job&&<div><span>Cycle remaining</span><strong>{Math.max(0,state.job.remaining).toFixed(1)}s</strong></div>}</div>}
 <div className="pd-connection-list"><h3>Connections</h3>{b.links.filter(l=>l.from===cell.id||l.to===cell.id).map(l=>{const other=b.cells.find(n=>n.id===(l.from===cell.id?l.to:l.from))!;return <button key={l.id} onClick={()=>onSelectLink(l.id)}><Link2 size={14}/><span>{l.from===cell.id?'To':'From'} {cellName(other)} #{other.id}<small>{ITEMS[l.item].short} · {l.carts} cart{l.carts>1?'s':''}{l.limit?` · limit ${l.limit}`:''}</small></span></button>;})}{!b.links.some(l=>l.from===cell.id||l.to===cell.id)&&<p>No material routes yet.</p>}</div>
 <div className="pd-cell-actions">{cell.kind!=='sink'&&<button className="pd-primary" disabled={!editable} onClick={onConnect}><Link2 size={16}/>Connect output</button>}<div><button className="pd-secondary" disabled={!editable} onClick={onMove}><Move size={15}/>Move cell</button><button className="pd-secondary" disabled={!editable} onClick={onCopy}><Copy size={15}/>Copy</button></div><button className="pd-delete" disabled={!editable} onClick={onDelete}><Trash2 size={15}/>Remove cell · refund {CASH(cellCost(cell))}</button></div>
 </aside>;
}
