'use client';
import {type CSSProperties,type DragEvent} from 'react';
import {Package,Warehouse,Drill,Cog,Flame,Truck,Wrench,Settings2,Plus,Link2,GripVertical} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {COLS,ROWS,ITEMS,MACHINES,RECIPES,outputItem,accepts,cellName,stateLabel,cycle,inputCount,type Blueprint,type Run,type Cell,type Link,type MachineId} from '@/lib/process';
export const MACHINE_ICONS={lathe:Settings2,mill:Drill,partner:Truck,hobber:Drill,shaver:Cog,outside:Truck,carburizer:Flame,grinder:Settings2,nitrider:Flame,assembly:Wrench};
const W=138,H=108,PAD=15;
const pos=(c:Cell)=>({x:PAD+c.x*W+W/2,y:PAD+c.y*H+H/2});
function points(a:Cell,z:Cell){const p=pos(a),q=pos(z);if(p.x===q.x){const direction=Math.sign(q.y-p.y);return[{x:p.x,y:p.y+direction*49},{x:q.x,y:q.y-direction*53}];}const direction=Math.sign(q.x-p.x),start={x:p.x+direction*63,y:p.y},end={x:q.x-direction*67,y:q.y},middle=(start.x+end.x)/2;return[start,{x:middle,y:p.y},{x:middle,y:q.y},end];}
function path(a:Cell,z:Cell){return points(a,z).map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');}
function pointAt(a:Cell,z:Cell,progress:number){const p=points(a,z),lengths=p.slice(1).map((q,i)=>Math.hypot(q.x-p[i].x,q.y-p[i].y));let distance=lengths.reduce((n,v)=>n+v,0)*progress;for(let i=0;i<lengths.length;i++){if(lengths[i]&&distance<=lengths[i])return{x:p[i].x+(p[i+1].x-p[i].x)*distance/lengths[i],y:p[i].y+(p[i+1].y-p[i].y)*distance/lengths[i]};distance-=lengths[i];}return p.at(-1)!;}
export function ProcessFloor({b,run,selected,selectedLink,connecting,moving,placing,editable,onCell,onLink,onEmpty,onConnect,onMove}:{b:Blueprint;run:Run|null;selected:number|null;selectedLink:number|null;connecting:number|null;moving:number|null;placing:boolean;editable:boolean;onCell:(id:number)=>void;onLink:(id:number)=>void;onEmpty:(x:number,y:number)=>void;onConnect:(id:number)=>void;onMove:(id:number,x:number,y:number)=>void}){
 const origin=b.cells.find(c=>c.id===connecting);const drag=(event:DragEvent,id:number)=>{event.dataTransfer.setData('application/x-gear-cell',String(id));event.dataTransfer.effectAllowed='move';};
 return <div className="pd-floor-scroll"><div className={`pd-floor ${placing||moving?'pd-floor-placement':''} ${connecting?'pd-floor-linking':''}`} style={{width:COLS*W+PAD*2,height:ROWS*H+PAD*2}}>
 <svg className="pd-routes" viewBox={`0 0 ${COLS*W+PAD*2} ${ROWS*H+PAD*2}`}><defs><marker id="pd-route-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10Z" fill="context-stroke"/></marker></defs>{b.links.map(l=>{const a=b.cells.find(n=>n.id===l.from)!,z=b.cells.find(n=>n.id===l.to)!,selected=l.id===selectedLink;return <g key={l.id}><path d={path(a,z)} fill="none" stroke="transparent" strokeWidth="20" className="pd-route-hit" onClick={()=>onLink(l.id)} role="button" tabIndex={0} aria-label={`Inspect ${ITEMS[l.item].short} route from ${cellName(a)} ${a.id} to ${cellName(z)} ${z.id}`} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onLink(l.id);}}/><path d={path(a,z)} fill="none" stroke={ITEMS[l.item].color} strokeWidth={selected?4:2} opacity={selected?1:.6} markerEnd="url(#pd-route-arrow)" className="pd-route-line"/></g>;})}{run?.shipments.map(s=>{const l=b.links.find(l=>l.id===s.link)!;const a=b.cells.find(n=>n.id===l.from)!,z=b.cells.find(n=>n.id===l.to)!,p=pointAt(a,z,1-s.remaining/s.duration);return <g key={s.id} transform={`translate(${p.x},${p.y})`} className="pd-parcel"><circle r="7" fill="#111e2c" stroke={ITEMS[s.item].color} strokeWidth="2"/><circle r="3" fill={ITEMS[s.item].color}/></g>;})}</svg>
 {Array.from({length:COLS*ROWS},(_,i)=>{const x=i%COLS,y=Math.floor(i/COLS),cell=b.cells.find(n=>n.x===x&&n.y===y);return <div className="pd-tile" key={i} style={{left:PAD+x*W,top:PAD+y*H,width:W,height:H}} onDragOver={e=>{if(editable&&!cell){e.preventDefault();e.dataTransfer.dropEffect='move';}}} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData('application/x-gear-cell'));if(editable&&!cell&&Number.isInteger(id)&&id>0)onMove(id,x,y);}}>{!cell&&<button className="pd-empty" aria-label={`${String.fromCharCode(65+x)}${y+1}, empty bay${placing?', place cell':''}`} onClick={()=>onEmpty(x,y)} disabled={!editable}><span>{String.fromCharCode(65+x)}{y+1}</span><Plus size={15}/></button>}</div>;})}
 {b.cells.map(cell=>{const p=pos(cell),Icon=cell.kind==='machine'?MACHINE_ICONS[cell.machine]:cell.kind==='source'?Warehouse:cell.kind==='sink'?Package:Package,output=outputItem(cell),s=run?.states[cell.id],state=s?stateLabel(cell,s):'',compatible=origin&&cell.id!==origin.id&&accepts(cell,outputItem(origin)),busy=!!s?.job&&s.job.remaining>0,blocked=state.includes('blocked'),selectedCell=selected===cell.id;return <article key={cell.id} role="button" tabIndex={0} aria-label={`${cellName(cell)} ${cell.id}. ${s?state:cell.kind==='machine'?RECIPES[cell.recipe].name:ITEMS[cell.item].name}`} aria-pressed={selectedCell} className={`pd-cell ${selectedCell?'pd-cell-selected':''} ${compatible?'pd-cell-compatible':''} ${connecting===cell.id?'pd-cell-origin':''} ${moving===cell.id?'pd-cell-moving':''} ${busy?'pd-cell-working':''} ${blocked?'pd-cell-blocked':''}`} style={{left:p.x,top:p.y,'--cell-color':ITEMS[output].color} as CSSProperties} draggable={editable} onDragStart={e=>drag(e,cell.id)} onClick={()=>onCell(cell.id)} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onCell(cell.id);}}}><div className="pd-cell-head"><Icon size={17}/><span>{cell.kind==='machine'?MACHINES[cell.machine].short:cell.kind==='source'?'Supplier':cell.kind==='sink'?'Dispatch':'Buffer'}</span><small>#{cell.id}</small></div><strong>{ITEMS[output].short}</strong><div className="pd-cell-status">{s?<><i className={busy?'busy':blocked?'blocked':cell.kind==='machine'?'waiting':''}/>{state}</>:cell.kind==='machine'?`${cycle(cell).toFixed(1)}s cycle`:cell.kind==='source'?`Lot ${cell.lot} · every ${cell.interval}s`:cell.kind==='buffer'?`${cell.capacity} spaces`:'Contract delivery'}</div><div className="pd-cell-bottom"><span>{s?(cell.kind==='machine'?`${inputCount(s)} in · ${s.output} out`:cell.kind==='sink'?`${s.received} received`:`${s.output} on rack`):cell.kind==='machine'?`Buffer ${cell.capacity} / input`:'12 ft bay'}</span>{editable&&cell.kind!=='sink'&&<button title="Connect output" aria-label={`Connect output of ${cellName(cell)} ${cell.id}`} onClick={e=>{e.stopPropagation();onConnect(cell.id);}}><Link2 size={13}/></button>}</div>{s?.job&&<Progress className="pd-cycle-progress" value={Math.max(0,Math.min(100,(1-s.job.remaining/cycle(cell))*100))} aria-label={`${cellName(cell)} progress`}/>}</article>;})}
 </div></div>;
}
