'use client';
import {useEffect,useState} from 'react';
import {ArrowUp,ArrowRight,ArrowUpRight,Pause,Play,Plus,Truck,Users,Warehouse,Wrench,X,Search} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {CASH,ITEMS,ITEM_IDS,MACHINES,MACHINE_IDS,RECIPES,PLANS,stock,incoming,queueSize,planCost,missingMachines,equipmentCost,cycleSeconds,routeCapacity,upgradeCost,resaleValue,isVendor,transferTime,type Shop,type ShopAction,type MachineId,type ItemId} from '@/lib/shop';
type Props={g:Shop;perform:(a:ShopAction)=>void;disabled:boolean};
function NumberSetting({label,value,max=100,min=0,onChange,disabled=false}:{label:string;value:number;max?:number;min?:number;onChange:(n:number)=>void;disabled?:boolean}){
 const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);
 const commit=()=>{const n=Number(draft);if(draft!==''&&Number.isInteger(n)&&n>=min&&n<=max){if(n!==value)onChange(n);}else setDraft(String(value));};
 return <label className="shop-number-setting"><span>{label}</span><Input type="number" min={min} max={max} value={draft} disabled={disabled} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></label>;
}
export function CellControls({g,id,perform,disabled}:Props&{id:MachineId}){
 const s=g.stations[id],m=MACHINES[id];
 return <div className="shop-cell-controls"><div className="shop-control-row"><div><strong>Dispatch control</strong><small>{s.paused?'New jobs held; active cycles finish.':'Waiting jobs start as material arrives.'}</small></div><button className="shop-outline" disabled={disabled} onClick={()=>perform({type:'pause',machine:id})}>{s.paused?<Play size={14}/>:<Pause size={14}/>} {s.paused?'Resume':'Pause'}</button></div>
 <label className="shop-control-row"><span><strong>Strict queue order</strong><small>{s.strict?'A missing input holds every later job.':'Skip blocked jobs to keep the cell working.'}</small></span><Switch checked={s.strict} disabled={disabled} onCheckedChange={()=>perform({type:'queueMode',machine:id})} aria-label="Strict queue order"/></label>
 <div className="shop-control-row"><div><strong>Repeat stock limit</strong><small>Stop repeating when each output reaches this level. Queued work still runs.</small></div><NumberSetting label="Sets" min={1} value={s.limit} disabled={disabled} onChange={quantity=>perform({type:'buffer',machine:id,quantity})}/></div>
 {s.repeat.length>1&&<div className="shop-repeat-mix"><strong>Route mix assigned</strong>{[...new Set(s.repeat)].map(r=><span key={r}>{s.repeat.filter(v=>v===r).length} × {RECIPES[r].name}</span>)}<small>Crews rotate through available operations. Choosing a work recipe replaces this mix.</small></div>}
 {s.queue.length>0&&<div className="shop-work-orders"><h3>Waiting work orders</h3><p>Move work to the front, or remove it before it starts.</p>{s.queue.map((q,i)=><div className="shop-work-order" key={q.id}><span><strong>{q.qty} × {RECIPES[q.recipe].name}</strong><small>{i===0?'Next in line':`Position ${i+1}`}</small></span><button aria-label={`Prioritize ${RECIPES[q.recipe].name}`} title="Move to front" disabled={disabled||i===0} onClick={()=>perform({type:'priority',machine:id,id:q.id})}><ArrowUp size={16}/></button><button aria-label={`Remove ${RECIPES[q.recipe].name}`} title="Remove waiting work" disabled={disabled} onClick={()=>perform({type:'removeJob',machine:id,id:q.id})}><X size={16}/></button></div>)}</div>}
 <div className="shop-upgrade-card"><div><Wrench size={17}/><strong>{isVendor(id)?'Supplier service level':'Tooling & cycle upgrade'}</strong><span>{s.level}/3</span></div><p>{s.level?`Cycles run at ${(1+s.level*.25).toFixed(2)}× base speed.`:'Improve this cell without buying another machine.'} Upgrades apply to future jobs.</p><button className="shop-outline" disabled={disabled||s.level>=3||g.cash<upgradeCost(g,id)} onClick={()=>perform({type:'upgrade',machine:id})}>{s.level>=3?'Fully upgraded':`Upgrade to ${(1+(s.level+1)*.25).toFixed(2)}× · ${CASH(upgradeCost(g,id))}`}</button></div>
 <div className="shop-cell-rack"><h3>On this cell’s rack</h3>{ITEM_IDS.filter(item=>g.bins[id][item]>0).map(item=><div key={item}><span style={{color:ITEMS[item].color}}>{ITEMS[item].short}</span><strong>{g.bins[id][item]}</strong></div>)}{!ITEM_IDS.some(item=>g.bins[id][item]>0)&&<p>Empty. Completed parts stay here until their next operation or shipment.</p>}</div>
 {!isVendor(id)&&<details className="shop-sell-equipment"><summary>Used-equipment dealer</summary><p>Sell one idle machine for 60% of its installation price. Finish or clear work and turn off repeat first. Crew and tooling stay with the bay.</p><button className="shop-outline" disabled={disabled||!!s.jobs.length||!!s.queue.length||s.auto} onClick={()=>perform({type:'sellMachine',machine:id})}>Sell one {m.short.toLowerCase()} · {CASH(resaleValue(g,id))}</button></details>}
 </div>;
}
export function LogisticsSettings({g,perform,disabled}:Props){return <div className="shop-logistics-settings"><div><h3>Material handling</h3><p>Current rack-to-cell transfer: {(transferTime(g)/1000).toFixed(1)}s. Improve dispatch carts and handling for every production route.</p><button className="shop-outline" disabled={disabled||g.handling>=3||g.cash<800*(g.handling+1)} onClick={()=>perform({type:'handling'})}>{g.handling>=3?'Handling fully upgraded':`Upgrade handling · ${CASH(800*(g.handling+1))}`}</button></div><div><h3>Buyer cash reserve</h3><p>The buyer leaves this much cash available for processing fees and machinery.</p><NumberSetting label="Keep cash" value={g.reserve} max={10000} onChange={quantity=>perform({type:'reserve',quantity})} disabled={disabled}/></div></div>;}
export function RouteCompare({g,plan,setPlan}: {g:Shop;plan:string;setPlan:(p:string)=>void}){
 const alternatives=Object.entries(PLANS).filter(([,p])=>p.output===PLANS[plan].output);const capacity=routeCapacity(g,plan);
 return <><div className="shop-capacity"><span><strong>{capacity.perMinute.toFixed(1)}</strong> units/min potential</span><span><strong>{MACHINES[capacity.bottleneck].short}</strong> limiting cell</span><small>At installed speeds and capacity, with steady supplies and dedicated cells. Missing equipment assumes one base machine; shared recipes can reduce output.</small></div>{alternatives.length>1&&<div className="shop-comparison"><h3>Other ways to make it</h3><div className="shop-comparison-grid">{alternatives.map(([key,p])=>{const missing=missingMachines(g,key),investment=missing.reduce((n,id)=>n+equipmentCost(g,id),0);return <button key={key} aria-pressed={key===plan} onClick={()=>setPlan(key)}><span>{p.name.split(' · ').slice(1).join(' · ')||p.name}</span><strong>{CASH(ITEMS[p.output].sell-planCost(key))}<small> gross margin / unit</small></strong><small>{CASH(planCost(key))} material + process</small><em>{investment?`${CASH(investment)} equipment needed`:'Your shop can run this route'}</em></button>;})}</div></div>}</>;
}
const rawIds:ItemId[]=['billet','alloyBillet','casting','hardware','heavyCasting','heavyHardware','blank','alloy','bought','kit','heavyKit'];
const gearboxIds:ItemId[]=['utility','industrial','precision','hybrid','heavy'];
export function Stockroom({g,perform,disabled,quantity,setQuantity}:Props&{quantity:number;setQuantity:(n:number)=>void}){
 const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[express,setExpress]=useState(false);
 const ids=ITEM_IDS.filter(i=>(filter==='all'||filter==='stocked'&&(stock(g,i)>0||incoming(g,i)>0)||filter==='materials'&&rawIds.includes(i)||filter==='gears'&&!rawIds.includes(i)&&!gearboxIds.includes(i)||filter==='gearboxes'&&gearboxIds.includes(i))&&ITEMS[i].name.toLowerCase().includes(search.toLowerCase()));
 return <><div className="shop-stock-heading"><div><h2>Buy a part. Make it. Or add the next operation.</h2><p>Purchased intermediate gears cost more, but free up machine capacity. Gear sets and kits can be sold directly; unused purchases can be returned for half of list price.</p></div><div className="shop-quantity">{[1,5,10,25].map(n=><button key={n} aria-pressed={quantity===n} onClick={()=>setQuantity(n)}>{n}</button>)}</div></div>
 <div className="shop-stock-tools"><div className="shop-search"><Search size={16}/><Input value={search} placeholder="Find a material or product…" aria-label="Search inventory" onChange={e=>setSearch(e.target.value)}/></div><Select value={filter} onValueChange={setFilter}><SelectTrigger aria-label="Inventory filter"><SelectValue/></SelectTrigger><SelectContent>{[['all','All inventory'],['stocked','On hand / ordered'],['materials','Materials & components'],['gears','Gear sets'],['gearboxes','Gearboxes']].map(([v,n])=><SelectItem key={v} value={v}>{n}</SelectItem>)}</SelectContent></Select><label className="shop-express"><Switch checked={express} onCheckedChange={setExpress} aria-label="Express stock delivery"/><span>Express delivery<small>1.8s · +20% purchase cost</small></span></label></div>
 <div className="shop-inventory-wrap"><Table className="shop-inventory"><TableHeader><TableRow><TableHead>Material / product</TableHead><TableHead>On rack</TableHead><TableHead>In transit</TableHead><TableHead>Buy / sell</TableHead><TableHead>Automation & stock levels</TableHead></TableRow></TableHeader><TableBody>{ids.map(i=>{const item=ITEMS[i],have=stock(g,i),sellQty=Math.min(quantity,have),price=Math.ceil(item.buy*quantity*(express?1.2:1));return <TableRow key={i}><TableCell><div className="shop-stock-name"><i style={{background:item.color}}/><div><strong>{item.name}</strong><small>{item.detail}</small><span className="shop-item-prices">{item.buy?`Buy ${CASH(item.buy)} / unit`:''}{item.buy&&item.sell?' · ':''}{item.sell?`Sell ${CASH(item.sell)} / unit`:''}</span></div></div></TableCell><TableCell className="shop-stock-count">{have}</TableCell><TableCell><span>{g.moves.filter(m=>m.item===i).reduce((n,m)=>n+m.qty,0)||'—'}</span>{incoming(g,i)>0&&<small className="shop-transit-note">{incoming(g,i)} inbound</small>}</TableCell><TableCell><div className="shop-trade-actions">{item.buy>0&&<button className="shop-outline" disabled={disabled||g.cash<price} onClick={()=>perform({type:'buy',item:i,quantity,express})}>Buy {quantity} · {CASH(price)}</button>}{item.sell>0&&<button className="shop-outline" disabled={disabled||!have} onClick={()=>perform({type:'sell',item:i,quantity})}>Sell {sellQty} · {CASH(item.sell*sellQty)}</button>}{item.buy>0&&!item.sell&&<button className="shop-text-button" disabled={disabled||!have} onClick={()=>perform({type:'return',item:i,quantity})}>Return {sellQty} · {CASH(Math.floor(item.buy*.5)*sellQty)}</button>}</div></TableCell><TableCell><div className="shop-stock-automation">{item.buy>0&&<div><label className="shop-auto-stock"><Switch checked={g.restock[i]} disabled={disabled||!g.buyer} aria-label={`Automatically buy ${item.short}`} onCheckedChange={enabled=>perform({type:'restock',item:i,enabled})}/><span>{g.buyer?'Auto buy':'Hire buyer'}</span></label>{g.restock[i]&&<div className="shop-stock-targets"><NumberSetting label="Below" value={g.reorder[i]} disabled={disabled} onChange={quantity=>perform({type:'reorder',item:i,quantity})}/><ArrowRight size={12}/><NumberSetting label="Fill to" value={g.target[i]} disabled={disabled} onChange={quantity=>perform({type:'target',item:i,quantity})}/></div>}</div>}{item.sell>0&&<div className="shop-auto-sell"><label className="shop-auto-stock"><Switch checked={g.selling[i]} disabled={disabled||!g.clerk} aria-label={`Automatically sell ${item.short}`} onCheckedChange={enabled=>perform({type:'autosell',item:i,enabled})}/><span>{g.clerk?'Auto sell':'Hire clerk'}</span></label><NumberSetting label="Keep" value={g.keep[i]} disabled={disabled} onChange={quantity=>perform({type:'keep',item:i,quantity})}/></div>}</div></TableCell></TableRow>;})}{ids.length===0&&<TableRow><TableCell colSpan={5}>No matching inventory.</TableCell></TableRow>}</TableBody></Table></div>
 <div className="shop-staff-hire"><button className="shop-outline" disabled={disabled||g.buyer||g.cash<900} onClick={()=>perform({type:'hireBuyer'})}><Users size={16}/>{g.buyer?'Buyer hired':'Hire buyer · $900'}</button><button className="shop-outline" disabled={disabled||g.clerk||g.cash<700} onClick={()=>perform({type:'hireClerk'})}><Users size={16}/>{g.clerk?'Shipping clerk hired':'Hire shipping clerk · $700'}</button><p>Auto buying uses standard delivery and your reserve of {CASH(g.reserve)}. Avoid buying and selling the same item automatically unless you intend to trade it.</p></div><LogisticsSettings g={g} perform={perform} disabled={disabled}/></>;
}
export function DispatchBoard({g,selectCell}:{g:Shop;selectCell:(id:MachineId)=>void}){
 return <div className="shop-dispatch"><div className="shop-stock-heading"><div><h2>See where work is waiting.</h2><p>Pause a cell, change its priorities, upgrade its cycle, or add parallel capacity from its work panel.</p></div></div><div className="shop-dispatch-grid">{MACHINE_IDS.filter(id=>g.stations[id].count>0).map(id=>{const s=g.stations[id],util=s.jobs.length/s.count;return <button className="shop-dispatch-cell" key={id} onClick={()=>selectCell(id)}><div><strong>{MACHINES[id].short}</strong><ArrowUpRight size={17}/></div><p>{s.paused?'Paused':s.jobs.length?`${s.jobs.length}/${s.count} slots working`:s.queue.length?'Waiting for inputs':'Available capacity'}</p><div className="shop-dispatch-bar"><span style={{width:`${util*100}%`,background:MACHINES[id].color}}/></div><small>{queueSize(s)} queued · {s.completed} completed · {(1+s.level*.25).toFixed(2)}× cycle speed</small></button>;})}</div><div className="shop-movements"><h3>Material movements</h3>{g.moves.length?g.moves.map(m=><div key={m.id}><span style={{color:ITEMS[m.item].color}}>{m.qty} × {ITEMS[m.item].short}</span><span>{m.kind==='buy'?'Supplier':m.from==='receiving'?'Receiving':m.from==='shipping'?'Shipping':MACHINES[m.from].short} <ArrowRight size={12}/> {m.to==='receiving'?'Receiving':m.to==='shipping'?'Customer':MACHINES[m.to].short}</span><strong>{Math.max(0,Math.ceil((m.end-g.last)/1000))}s</strong></div>):<p>No material is moving. Queue work or order stock to start the next job.</p>}</div></div>;
}
