'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {newCareer,validCareer,type Career} from '@/lib/career';
export function useCareer(){
 const [data,setData]=useState<Career>(newCareer),ref=useRef(data);const[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[saveError,setSaveError]=useState(''),[status,setStatus]=useState('Opening'),[conflict,setConflict]=useState(false);
 const pendingDirty=useRef(false);const ready=useRef(false),blocked=useRef(false),revision=useRef(0),busy=useRef(false),pending=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const save=useCallback(async function save(keepalive=false){if(!ready.current||blocked.current)return;if(busy.current){pending.current=true;return;}busy.current=true;pendingDirty.current=false;setStatus('Saving');try{const response=await fetch('/api/career',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:ref.current,revision:revision.current}),keepalive});const d=await response.json() as {revision:number;error?:string};if(response.status===409){blocked.current=true;setConflict(true);}if(!response.ok)throw new Error(d.error||'Could not save shop.');revision.current=d.revision;setSaveError('');setStatus('Saved');}catch(e){pendingDirty.current=true;setSaveError(e instanceof Error?e.message:'Could not save.');setStatus('Not saved');}finally{busy.current=false;if(pending.current&&!blocked.current){pending.current=false;void save();}}},[]);
 const change=useCallback((fn:(s:Career)=>Career)=>{if(!ready.current||blocked.current)return;ref.current=fn(ref.current);setData(ref.current);pendingDirty.current=true;setStatus('Saving');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void save(),650);},[save]);
 const load=useCallback(async()=>{setError('');try{const response=await fetch('/api/career',{cache:'no-store'});const d=await response.json() as {state:unknown;revision:number;error?:string};if(!response.ok)throw new Error(d.error||'Could not load shop.');if(!validCareer(d.state))throw new Error('Could not read the saved shop.');ref.current=d.state;setData(d.state);revision.current=d.revision;ready.current=true;blocked.current=false;setLoaded(true);setConflict(false);setStatus('Saved');}catch(e){setError(e instanceof Error?e.message:'Could not load shop.');}},[]);
 useEffect(()=>{void load();const autosave=setInterval(()=>{if(ready.current&&pendingDirty.current)void save();},15000);const close=()=>void save(true);window.addEventListener('pagehide',close);const visibility=()=>{if(document.hidden)void save(true);};document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(autosave);window.removeEventListener('pagehide',close);document.removeEventListener('visibilitychange',visibility);if(timer.current)clearTimeout(timer.current);};},[load,save]);
 return{data,ref,change,loaded,error,saveError,status,conflict,save,load};
}
