import {ITEMS,ITEM_IDS,MACHINES,MACHINE_IDS,RECIPES,PLANS,planMaterials,type ItemId,type MachineId,type Stock} from './shop.ts';
export {ITEMS,ITEM_IDS,MACHINES,MACHINE_IDS,RECIPES,PLANS};
export type {ItemId,MachineId};
export const DT=.05;
export const PRICE=4;
export const ROLES={machinist:{name:'Machinist',wage:160,fee:450,detail:'Operates turning, cutting, finishing, and heat-treat equipment.'},assembler:{name:'Assembly technician',wage:150,fee:400,detail:'Builds and tests reducers at an assembly bench.'},engineer:{name:'Gear engineer',wage:260,fee:800,detail:'Reviews prints, reverse-engineers parts, and develops new designs.'},inspector:{name:'Quality inspector',wage:190,fee:500,detail:'Inspects completed lots and releases technical deliverables.'}} as const;
export type Role=keyof typeof ROLES;
export const ROLE_IDS=Object.keys(ROLES) as Role[];
export type OwnerRole='auto'|Role|'office';
export type Kind='print'|'reverse'|'design'|'assembly'|'stock';
export const KIND_NAMES:Record<Kind,string>={print:'Build to print',reverse:'Reverse engineering',design:'Engineered design',assembly:'Assembly order',stock:'Catalog stock'};
export type Template={id:string;name:string;client:string;kind:Exclude<Kind,'stock'>;products:ItemId[];qty:number;days:number;rep:number;brief:string;service:boolean;engineeringFee:number};
export const INQUIRIES:Template[]=[
 {id:'farm-spares',name:'Change-gear replacement lot',client:'County Machinery',kind:'print',products:['rough'],qty:12,days:5,rep:0,brief:'Customer supplies a checked drawing for matched 8620 pinion and wheel sets. Cut and deburr to print.',service:false,engineeringFee:0},
 {id:'mixer-sets',name:'Mixer drive gear sets',client:'Atlas Process',kind:'print',products:['shaved'],qty:8,days:6,rep:0,brief:'Repeat batch of soft-finished gears. The customer wants clean tooth finish and a dimensional inspection report.',service:false,engineeringFee:0},
 {id:'bench-assembly',name:'Conveyor reducer assembly',client:'Dockside Handling',kind:'assembly',products:['utility'],qty:4,days:6,rep:0,brief:'Single-stage utility reducers. You may buy catalog gears or manufacture shaved sets; fit, assemble, and test in your shop.',service:false,engineeringFee:0},
 {id:'obsolete-gear',name:'Obsolete feeder gear',client:'Westline Service',kind:'reverse',products:['shaved'],qty:4,days:9,rep:0,brief:'Only a worn sample exists. Recover its geometry, produce a controlled drawing, then manufacture a replacement lot.',service:false,engineeringFee:2600},
 {id:'concept-drive',name:'Packaging drive design',client:'Larch Packaging',kind:'design',products:['utility','industrial'],qty:1,days:8,rep:0,brief:'Design a compact single-stage drive. Choose a low-cost shaved-gear design or a hardened industrial design. This order is for drawings and a bill of materials.',service:true,engineeringFee:5700},
 {id:'hard-spares',name:'Precision replacement gears',client:'Horizon Motion',kind:'print',products:['ground'],qty:6,days:8,rep:8,brief:'Case-hardened and hard-ground matched sets. Decide whether to bring grinding and heat treatment inside or subcontract them.',service:false,engineeringFee:0},
 {id:'reverse-hard',name:'Legacy reducer gear recovery',client:'North Coast Repair',kind:'reverse',products:['ground'],qty:5,days:10,rep:12,brief:'Reverse-engineer a damaged hardened gear set. Recover the part definition and supply inspected replacements.',service:false,engineeringFee:3900},
 {id:'designed-package',name:'Custom machine-tool drive',client:'Meridian Machine Tools',kind:'design',products:['precision','hybrid'],qty:3,days:12,rep:15,brief:'Develop and manufacture a reducer package. A single-stage precision build uses shop-made gears; the two-stage alternative mixes a custom stage with a catalog stage.',service:false,engineeringFee:6500},
 {id:'industrial-lot',name:'Industrial drive production lot',client:'Larch Packaging',kind:'assembly',products:['industrial'],qty:6,days:9,rep:18,brief:'Build a repeat production lot of hardened industrial reducers and record final inspection results.',service:false,engineeringFee:0},
 {id:'heavy-drive',name:'Two-stage winch drives',client:'North Coast Marine',kind:'design',products:['heavy'],qty:3,days:14,rep:28,brief:'Engineer a two-stage reducer with two nitrided gear sets per unit. Include design records, assembly, and final test.',service:false,engineeringFee:7800},
];
export type Offer={id:number;template:string;qty:number;created:number;expires:number;repeat:boolean};
export type Person={id:number;name:string;role:Role;skill:number;wage:number;assignment:number;hired:number};
export type Equipment={id:number;type:MachineId;bay:number;used:boolean;level:number;paid:number;lastPart:string;lastRecipe:string;completed:number;busy:number;paused:boolean};
export type Task={recipe:string;total:number;done:number};
export type WorkOrder={id:number;name:string;client:string;kind:Kind;part:string;item:ItemId;qty:number;value:number;deposit:number;accepted:number;due:number;plan:string;terms:'flexible'|'standard'|'rush';service:boolean;engineering:'inhouse'|'partner';engineeringTotal:number;engineeringLeft:number;engineeringCharged:boolean;engineeringReady:boolean;qaLeft:number;released:boolean;paused:boolean;stage:'planning'|'engineering'|'production'|'inspection'|'ready'|'shipping'|'complete';transferBatch:number;tasks:Task[];bins:Record<string,Partial<Stock>>;cost:number;finished:number;paid:number};
export type Work={id:number;job:number;task:number;equipment:number;vendor:MachineId|null;worker:number;qty:number;start:number;finish:number};
export type Movement={id:number;job:number;item:ItemId;qty:number;from:string;to:string;start:number;end:number;kind:'feed'|'purchase'|'shipment'};
export type Drawing={part:string;name:string;item:ItemId;origin:Kind;created:number;runs:number};
export type Ledger={id:number;time:number;amount:number;category:string;text:string};
export type Career={version:1;name:string;time:number;cash:number;debt:number;arrears:number;revenue:number;expenses:number;reputation:number;nextId:number;floor:number;cad:boolean;metrology:boolean;owner:OwnerRole;autoShip:boolean;equipment:Equipment[];people:Person[];offers:Offer[];jobs:WorkOrder[];work:Work[];moves:Movement[];inventory:Partial<Stock>;drawings:Drawing[];ledger:Ledger[];delivered:number;history:{day:number;cash:number;revenue:number;expenses:number}[]};
const availableTemplates=(g:Career)=>INQUIRIES.filter(t=>t.rep<=g.reputation);
export function newCareer():Career{const g:Career={version:1,name:'Night Shift Gear Co.',time:0,cash:25000,debt:0,arrears:0,revenue:0,expenses:0,reputation:0,nextId:1,floor:0,cad:false,metrology:false,owner:'auto',autoShip:true,equipment:[],people:[],offers:[],jobs:[],work:[],moves:[],inventory:{},drawings:[],ledger:[],delivered:0,history:[]};log(g,25000,'Capital','Owner investment. The lease includes six empty machine bays.');refreshOffers(g);return g;}
export const day=(g:Career)=>Math.floor(g.time/8)+1;
export const clock=(hours:number)=>`Day ${Math.floor(hours/8)+1} · ${String(8+Math.floor(hours%8)).padStart(2,'0')}:${String(Math.round((hours%1)*60)%60).padStart(2,'0')}`;
export const vendor=(id:MachineId)=>id==='outside'||id==='partner';
export function machinePrice(id:MachineId,used=false){return Math.round(MACHINES[id].cost*10*(used?.68:1));}
export function bays(g:Career){return 6+g.floor*6;}
export function dailyOverhead(g:Career){return 120+g.floor*140+g.people.reduce((n,p)=>n+p.wage,0)+Math.ceil(g.debt*.002);}
export function creditLimit(g:Career){return Math.min(50000,10000+g.reputation*400);}
export function partKey(t:Template,item:ItemId){return t.id+':'+item;}
export function routeChoices(item:ItemId){return Object.entries(PLANS).filter(([,p])=>p.output===item);}
export function neededEquipment(g:Career,plan:string){return [...new Set(PLANS[plan].steps.map(([r])=>RECIPES[r].machine))].filter(id=>!vendor(id)&&!g.equipment.some(m=>m.type===id));}
export function defaultRoute(g:Career,item:ItemId){return routeChoices(item).sort(([a],[b])=>neededEquipment(g,a).reduce((n,id)=>n+machinePrice(id,true),0)-neededEquipment(g,b).reduce((n,id)=>n+machinePrice(id,true),0))[0]?.[0]||'rough';}
export function runningJobs(g:Career){return g.jobs.filter(j=>j.stage!=='complete');}
export function materialCost(plan:string,qty:number){return Object.entries(planMaterials(plan,qty)).reduce((n,[i,q])=>n+ITEMS[i as ItemId].buy*q!*PRICE,0);}
export function processCost(plan:string,qty:number){return PLANS[plan].steps.reduce((n,[r,q])=>n+RECIPES[r].fee*q*qty*PRICE,0);}
export function engineeringHours(g:Career,t:Template,item:ItemId){if(g.drawings.some(d=>d.part===partKey(t,item)))return .4;return t.kind==='reverse'?10:t.kind==='design'?18:t.kind==='assembly'?.6:.8;}
export function partnerEngineering(j:Pick<WorkOrder,'kind'|'engineeringTotal'>){return j.kind==='reverse'?1800:j.kind==='design'?3400:200;}
export function quoteValue(g:Career,t:Template,qty:number,item:ItemId,terms:'flexible'|'standard'|'rush'){const productValue=t.service?0:ITEMS[item].sell*PRICE*qty*1.4;const fee=t.engineeringFee*(t.kind==='design'&&item!==t.products[0]?1.2:1)*(g.drawings.some(d=>d.part===partKey(t,item))?.55:1);return Math.round((productValue+fee)*(terms==='rush'?1.22:terms==='flexible'?.9:1));}
export function jobStock(j:WorkOrder,item:ItemId){return Object.values(j.bins).reduce((n,b)=>n+(b[item]||0),0);}
export function jobMissing(g:Career,j:WorkOrder){if(j.service)return[];return Object.entries(planMaterials(j.plan,j.qty)).map(([i,n])=>{const item=i as ItemId;const inTransit=g.moves.filter(m=>m.kind==='purchase'&&m.job===j.id&&m.item===item).reduce((sum,m)=>sum+m.qty,0);const consumed=j.tasks.reduce((sum,t)=>sum+(RECIPES[t.recipe].input[item]||0)*(t.done+g.work.filter(w=>w.job===j.id&&w.task===j.tasks.indexOf(t)).reduce((a,w)=>a+w.qty,0)),0);return {item,qty:Math.max(0,n!-jobStock(j,item)-inTransit-consumed)};}).filter(n=>n.qty>0);}
export function missingPurchaseCost(g:Career,j:WorkOrder){return jobMissing(g,j).reduce((n,m)=>n+Math.max(0,m.qty-(g.inventory[m.item]||0))*ITEMS[m.item].buy*PRICE,0);}
function log(g:Career,amount:number,category:string,text:string){g.ledger.unshift({id:g.nextId++,time:g.time,amount,category,text});g.ledger=g.ledger.slice(0,120);}
function pay(g:Career,amount:number,category:string,text:string,job?:WorkOrder){if(g.cash+.0001<amount)return false;g.cash-=amount;g.expenses+=amount;if(job)job.cost+=amount;if(amount)log(g,-amount,category,text);return true;}
function receive(g:Career,amount:number,category:string,text:string){g.cash+=amount;log(g,amount,category,text);if(g.arrears>0){const paid=Math.min(g.arrears,g.cash);g.cash-=paid;g.arrears-=paid;log(g,-paid,'Overdue bills','Past-due operating bills paid.');}}
function refreshOffers(g:Career){g.offers=g.offers.filter(o=>o.expires>g.time);const templates=availableTemplates(g);for(const t of templates){if(g.offers.some(o=>o.template===t.id)||runningJobs(g).some(j=>j.part.startsWith(t.id+':')))continue;const repeat=g.drawings.some(d=>d.part.startsWith(t.id+':'));const repeatFactor=repeat?1+Math.min(2,Math.floor(g.delivered/5))*.25:1;g.offers.push({id:g.nextId++,template:t.id,qty:t.service?1:Math.round(t.qty*repeatFactor),created:g.time,expires:g.time+64,repeat});}g.offers=g.offers.slice(0,10);}
function engFacility(g:Career,j:WorkOrder){return j.kind==='reverse'?g.metrology||g.drawings.some(d=>d.part===j.part):j.kind==='design'?g.cad||g.drawings.some(d=>d.part===j.part):true;}
export function engineeringBlocked(g:Career,j:WorkOrder){if(j.engineering==='partner')return !j.engineeringCharged?`Outside engineering needs $${partnerEngineering(j).toLocaleString()}.`:'';if(!engFacility(g,j))return j.kind==='reverse'?'In-house recovery needs the metrology package.':'In-house design needs the engineering software package.';if(!g.people.some(p=>p.role==='engineer')&&!['auto','engineer'].includes(g.owner))return 'Assign the owner to engineering or hire a gear engineer.';return '';}
function locationBay(g:Career,loc:string){if(loc==='stores')return{x:-1,y:0};if(loc==='vendor')return{x:6,y:1};if(loc==='dispatch')return{x:6,y:2};const e=g.equipment.find(e=>'m'+e.id===loc);return e?{x:e.bay%6,y:Math.floor(e.bay/6)}:{x:0,y:0};}
function transfer(g:Career,j:WorkOrder,item:ItemId,qty:number,to:string){let remaining=qty,maxTime=0;for(const[from,bin]of Object.entries(j.bins)){const take=Math.min(remaining,bin[item]||0);if(!take)continue;bin[item]=(bin[item]||0)-take;remaining-=take;const a=locationBay(g,from),z=locationBay(g,to),duration=.05+(Math.abs(a.x-z.x)+Math.abs(a.y-z.y))*.015;maxTime=Math.max(maxTime,duration);g.moves.push({id:g.nextId++,job:j.id,item,qty:take,from,to,start:g.time,end:g.time+duration,kind:'feed'});if(!remaining)break;}return maxTime;}
function freeWorkers(g:Career,role:Role,equipment=0){const busy=new Set(g.work.map(w=>w.worker));const people=g.arrears<=0?g.people.filter(p=>p.role===role&&!busy.has(p.id)&&(!p.assignment||p.assignment===equipment)).map(p=>({id:p.id,skill:p.skill})):[];if(!busy.has(0)&&(g.owner===role||g.owner==='auto'))people.push({id:0,skill:.8});return people;}
function archiveDrawing(g:Career,j:WorkOrder){if(!g.drawings.some(d=>d.part===j.part))g.drawings.push({part:j.part,name:j.name,item:j.item,origin:j.kind,created:g.time,runs:0});}
function tasksDone(j:WorkOrder){return j.tasks.every(t=>t.done>=t.total);}
function taskAvailable(g:Career,j:WorkOrder,index:number){const task=j.tasks[index],r=RECIPES[task.recipe];const active=g.work.filter(w=>w.job===j.id&&w.task===index).reduce((n,w)=>n+w.qty,0);const remaining=task.total-task.done-active,quantity=vendor(r.machine)?Math.min(remaining,j.transferBatch||remaining):1;return remaining>0&&Object.entries(r.input).every(([i,n])=>jobStock(j,i as ItemId)>=n!*quantity);}
function startOperation(g:Career,j:WorkOrder,index:number,equipment:Equipment|null){const task=j.tasks[index],r=RECIPES[task.recipe],outside=vendor(r.machine);const worker=outside?{id:-1,skill:1}:freeWorkers(g,r.machine==='assembly'?'assembler':'machinist',equipment!.id)[0];if(!worker)return false;let qty=1;if(outside){const remaining=task.total-task.done-g.work.filter(w=>w.job===j.id&&w.task===index).reduce((n,w)=>n+w.qty,0);qty=Math.min(remaining,j.transferBatch||remaining);for(const[i,n]of Object.entries(r.input))qty=Math.min(qty,Math.floor(jobStock(j,i as ItemId)/n!));}
 const fee=r.fee*qty*PRICE+(outside?20:equipment!.used?5:2);if(!pay(g,fee,'Production',`${j.name}: ${r.name}${qty>1?' · batch '+qty:''}`,j))return false;
 const to=outside?'vendor':'m'+equipment!.id;let movement=0;for(const[i,n]of Object.entries(r.input))movement=Math.max(movement,transfer(g,j,i as ItemId,n!*qty,to));
 const setup=outside?0:equipment!.lastPart===j.part&&equipment!.lastRecipe===task.recipe?0:g.drawings.find(d=>d.part===j.part)?.runs? .25:.65;
 const duration=outside?r.seconds/6+qty*.04:(r.seconds/35+setup)/((equipment!.used?.8:1)*(1+equipment!.level*.25)*worker.skill);
 g.work.push({id:g.nextId++,job:j.id,task:index,equipment:equipment?.id||0,vendor:outside?r.machine:null,worker:worker.id,qty,start:g.time+movement,finish:g.time+movement+duration});if(equipment){equipment.lastPart=j.part;equipment.lastRecipe=task.recipe;}return true;}
function pump(g:Career){
 for(const j of g.jobs){if(!j.released||j.paused||j.stage==='complete'||j.stage==='shipping')continue;
  if(!j.engineeringReady){j.stage='engineering';if(j.engineering==='partner'&&!j.engineeringCharged)j.engineeringCharged=pay(g,partnerEngineering(j),'Engineering',`Outside engineering: ${j.name}`,j);continue;}
  if(j.service||tasksDone(j)){j.stage=j.qaLeft>0?'inspection':'ready';continue;}j.stage='production';
 }
 for(const e of g.equipment){if(e.paused||g.work.some(w=>w.equipment===e.id))continue;for(const j of g.jobs){if(j.stage!=='production'||j.paused)continue;let done=false;for(let index=j.tasks.length-1;index>=0;index--){if(RECIPES[j.tasks[index].recipe].machine===e.type&&taskAvailable(g,j,index)&&startOperation(g,j,index,e)){done=true;break;}}if(done)break;}}
 for(const type of ['outside','partner'] as MachineId[]){let active=g.work.filter(w=>w.vendor===type).length;for(const j of g.jobs){if(active>=2)break;if(j.stage!=='production'||j.paused)continue;for(let index=j.tasks.length-1;index>=0&&active<2;index--)if(RECIPES[j.tasks[index].recipe].machine===type&&taskAvailable(g,j,index)&&startOperation(g,j,index,null))active++;}}
 for(const j of g.jobs)if(j.stage==='ready'&&!j.paused){if(j.kind==='stock'){g.inventory[j.item]=(g.inventory[j.item]||0)+j.qty;j.stage='complete';j.finished=g.time;j.bins={};archiveDrawing(g,j);g.drawings.find(d=>d.part===j.part)!.runs++;log(g,0,'Production',`${j.qty} ${ITEMS[j.item].short} added to house stock.`);}else if(g.autoShip)dispatch(g,j);}
}
function dispatch(g:Career,j:WorkOrder){if(j.stage!=='ready')return false;j.stage='shipping';g.moves.push({id:g.nextId++,job:j.id,item:j.item,qty:j.service?1:j.qty,from:'dispatch',to:'customer',start:g.time,end:g.time+.25,kind:'shipment'});return true;}
function settleJob(g:Career,j:WorkOrder){const lateDays=Math.max(0,(g.time-j.due)/8),deduction=Math.min(.25,lateDays*.04),value=Math.round(j.value*(1-deduction));j.paid=value;j.finished=g.time;j.stage='complete';receive(g,Math.max(0,value-j.deposit),'Customer payment',`${j.client}: ${j.name}${deduction?' · late adjustment':''}`);g.revenue+=value;g.delivered++;g.reputation=Math.max(0,Math.min(100,g.reputation+(lateDays? -Math.min(6,Math.ceil(lateDays)):j.kind==='design'||j.kind==='reverse'?5:3)));const drawing=g.drawings.find(d=>d.part===j.part);if(drawing)drawing.runs++;j.bins={};refreshOffers(g);}
export function advanceCareer(previous:Career,hours:number):Career {const g=structuredClone(previous),steps=Math.max(0,Math.min(3200,Math.round(hours/DT)));for(let n=0;n<steps;n++){
 pump(g);const usedWorkers=new Set<number>();
 for(const role of ['engineer','inspector'] as Role[]){const staff=freeWorkers(g,role).filter(w=>!usedWorkers.has(w.id));for(const worker of staff){const j=g.jobs.find(j=>!j.paused&&j.released&&(role==='engineer'?j.stage==='engineering'&&j.engineering==='inhouse'&&engFacility(g,j):j.stage==='inspection'));if(!j)continue;usedWorkers.add(worker.id);if(role==='engineer')j.engineeringLeft=Math.max(0,j.engineeringLeft-DT*worker.skill);else j.qaLeft=Math.max(0,j.qaLeft-DT*worker.skill);}}
 const beforeDay=Math.floor(g.time/8);g.time=Number((g.time+DT).toFixed(6));
 for(const j of g.jobs){if(j.stage==='engineering'&&!j.paused&&j.engineering==='partner'&&j.engineeringCharged)j.engineeringLeft=Math.max(0,j.engineeringLeft-DT*(j.kind==='design'?.6:.8));if(j.stage==='engineering'&&j.engineeringLeft<=.000001){j.engineeringReady=true;archiveDrawing(g,j);}}
 for(const e of g.equipment)if(g.work.some(w=>w.equipment===e.id))e.busy+=DT;
 const finished=g.work.filter(w=>w.finish<=g.time+.000001);g.work=g.work.filter(w=>w.finish>g.time+.000001);for(const w of finished){const j=g.jobs.find(j=>j.id===w.job)!,task=j.tasks[w.task],item=RECIPES[task.recipe].output,loc=w.vendor?'vendor':'m'+w.equipment;task.done+=w.qty;j.bins[loc]??={};j.bins[loc][item]=(j.bins[loc][item]||0)+w.qty;const e=g.equipment.find(e=>e.id===w.equipment);if(e)e.completed+=w.qty;}
 const arrived=g.moves.filter(m=>m.end<=g.time+.000001);g.moves=g.moves.filter(m=>m.end>g.time+.000001);for(const m of arrived){const j=g.jobs.find(j=>j.id===m.job);if(m.kind==='purchase'){if(j){j.bins.stores??={};j.bins.stores[m.item]=(j.bins.stores[m.item]||0)+m.qty;}else g.inventory[m.item]=(g.inventory[m.item]||0)+m.qty;}if(m.kind==='shipment'&&j)settleJob(g,j);}
 if(Math.floor(g.time/8)>beforeDay){const expenses=dailyOverhead(g),paid=Math.min(g.cash,expenses);g.cash-=paid;g.arrears+=expenses-paid;g.expenses+=expenses;log(g,-expenses,'Daily overhead',`Rent, payroll, and interest${g.arrears?' · unpaid balance $'+Math.round(g.arrears):''}`);g.history.push({day:day(g)-1,cash:g.cash,revenue:g.revenue,expenses:g.expenses});g.history=g.history.slice(-60);refreshOffers(g);}
 }pump(g);const complete=g.jobs.filter(j=>j.stage==='complete').sort((a,b)=>b.finished-a.finished).slice(0,80);g.jobs=[...g.jobs.filter(j=>j.stage!=='complete'),...complete];return g;}
export type CareerAction=
 |{type:'buyMachine';machine:MachineId;used:boolean;bay:number}
 |{type:'sellMachine'|'upgradeMachine'|'pauseMachine';id:number}
 |{type:'moveMachine';id:number;bay:number}
 |{type:'hire';role:Role}|{type:'dismiss';id:number}|{type:'assign';id:number;equipment:number}
 |{type:'owner';role:OwnerRole}|{type:'autoShip';enabled:boolean}
 |{type:'facility';facility:'cad'|'metrology'|'floor'}
 |{type:'accept';offer:number;item:ItemId;plan:string;terms:'flexible'|'standard'|'rush';engineering:'inhouse'|'partner'}
 |{type:'release'|'pauseJob'|'prioritize'|'dispatch';id:number}
 |{type:'jobRoute';id:number;plan:string}|{type:'engineeringMode';id:number;mode:'inhouse'|'partner'}
 |{type:'supplyJob';id:number;express:boolean}|{type:'batchSize';id:number;qty:number}
 |{type:'borrow'|'repay';amount:number}|{type:'rename';name:string}
 |{type:'buyStock'|'sellStock';item:ItemId;qty:number}
 |{type:'stockLot';item:ItemId;qty:number;plan:string};
const names=['Morgan','Jordan','Sam','Casey','Alex','Riley','Taylor','Drew','Quinn','Avery','Parker','Cameron'];
export function isCareerAction(a:unknown):a is CareerAction {if(!a||typeof a!=='object')return false;const x=a as Record<string,unknown>,id=Number.isSafeInteger(x.id)&&Number(x.id)>0,plan=typeof x.plan==='string'&&Object.hasOwn(PLANS,x.plan),item=ITEM_IDS.includes(x.item as ItemId);switch(x.type){case'buyMachine':return MACHINE_IDS.includes(x.machine as MachineId)&&!vendor(x.machine as MachineId)&&typeof x.used==='boolean'&&Number.isInteger(x.bay)&&Number(x.bay)>=0&&Number(x.bay)<18;case'sellMachine':case'upgradeMachine':case'pauseMachine':case'dismiss':case'release':case'pauseJob':case'prioritize':case'dispatch':return id;case'moveMachine':return id&&Number.isInteger(x.bay)&&Number(x.bay)>=0&&Number(x.bay)<18;case'hire':return ROLE_IDS.includes(x.role as Role);case'assign':return id&&Number.isSafeInteger(x.equipment)&&Number(x.equipment)>=0;case'owner':return [...ROLE_IDS,'auto','office'].includes(String(x.role));case'autoShip':return typeof x.enabled==='boolean';case'facility':return ['cad','metrology','floor'].includes(String(x.facility));case'accept':return Number.isSafeInteger(x.offer)&&item&&plan&&['flexible','standard','rush'].includes(String(x.terms))&&['inhouse','partner'].includes(String(x.engineering));case'jobRoute':return id&&plan;case'engineeringMode':return id&&['inhouse','partner'].includes(String(x.mode));case'supplyJob':return id&&typeof x.express==='boolean';case'batchSize':return id&&[0,1,5,10].includes(Number(x.qty))&&typeof x.qty==='number';case'borrow':case'repay':return Number.isInteger(x.amount)&&Number(x.amount)>0&&Number(x.amount)<=50000;case'rename':return typeof x.name==='string'&&x.name.trim().length>=1&&x.name.trim().length<=60;case'buyStock':case'sellStock':return item&&Number.isInteger(x.qty)&&Number(x.qty)>0&&Number(x.qty)<=100;case'stockLot':return item&&plan&&Number.isInteger(x.qty)&&Number(x.qty)>0&&Number(x.qty)<=50;default:return false;}}
export function careerAction(previous:Career,a:CareerAction):{state:Career;ok:boolean;message:string}{const g=structuredClone(previous);if(!isCareerAction(a))return{state:g,ok:false,message:'Invalid shop action.'};let ok=false,message='';const job='id'in a?g.jobs.find(j=>j.id===a.id):undefined;const e='id'in a?g.equipment.find(e=>e.id===a.id):undefined;
 switch(a.type){
 case'buyMachine':if(a.bay>=bays(g)||g.equipment.some(e=>e.bay===a.bay)){message='Choose an available machine bay.';break;}if(pay(g,machinePrice(a.machine,a.used),'Equipment',`${a.used?'Used':'New'} ${MACHINES[a.machine].name}`)){g.equipment.push({id:g.nextId++,type:a.machine,bay:a.bay,used:a.used,level:0,paid:machinePrice(a.machine,a.used),lastPart:'',lastRecipe:'',completed:0,busy:0,paused:false});ok=true;message='Equipment installed. It remains part of your shop.';}break;
 case'sellMachine':if(e&&!g.work.some(w=>w.equipment===e.id)){receive(g,Math.floor(e.paid*.6),'Asset sale',`${MACHINES[e.type].name} sold`);g.equipment=g.equipment.filter(m=>m.id!==e.id);for(const p of g.people)if(p.assignment===e.id)p.assignment=0;ok=true;}else message='Let the current cycle finish before selling the machine.';break;
 case'upgradeMachine':if(e&&e.level<2&&pay(g,Math.ceil(machinePrice(e.type)*.3),'Equipment',`Tooling upgrade: ${MACHINES[e.type].short}`)){e.level++;ok=true;}break;
 case'pauseMachine':if(e){e.paused=!e.paused;ok=true;}break;
 case'moveMachine':if(e&&a.bay<bays(g)&&!g.equipment.some(m=>m.bay===a.bay)&&!g.work.some(w=>w.equipment===e.id)&&pay(g,250,'Rigging',`Move ${MACHINES[e.type].short}`)){e.bay=a.bay;ok=true;}break;
 case'hire':if(g.people.length>=24){message='The staffing limit is 24 people.';break;}if(pay(g,ROLES[a.role].fee,'Recruiting',`Hire ${ROLES[a.role].name}`)){g.people.push({id:g.nextId++,name:names[g.people.length%names.length]+' '+String(g.nextId).padStart(2,'0'),role:a.role,skill:1.15,wage:ROLES[a.role].wage,assignment:0,hired:g.time});ok=true;message=`${ROLES[a.role].name} hired. Daily payroll now includes $${ROLES[a.role].wage}.`;}break;
 case'dismiss':{const p=g.people.find(p=>p.id===a.id);if(p&&!g.work.some(w=>w.worker===p.id)&&pay(g,p.wage,'Staffing',`Final pay: ${p.name}`)){g.people=g.people.filter(p=>p.id!==a.id);ok=true;}else message='Finish their active cycle and allow one day of final pay.';break;}
 case'assign':{const p=g.people.find(p=>p.id===a.id),machine=g.equipment.find(m=>m.id===a.equipment);if(p&&(a.equipment===0||machine&&(p.role==='machinist'&&machine.type!=='assembly'||p.role==='assembler'&&machine.type==='assembly'))){p.assignment=a.equipment;ok=true;}break;}
 case'owner':g.owner=a.role;ok=true;break;
 case'autoShip':g.autoShip=a.enabled;ok=true;break;
 case'facility':if(a.facility==='floor'){if(g.floor<2&&pay(g,15000*(g.floor+1),'Expansion','Lease six additional machine bays')){g.floor++;ok=true;}}else if(!g[a.facility]&&pay(g,a.facility==='cad'?5500:8000,'Engineering assets',a.facility==='cad'?'Engineering software and design workstation':'Gear metrology and sample-recovery package')){g[a.facility]=true;ok=true;}break;
 case'accept':{const o=g.offers.find(o=>o.id===a.offer),t=o&&INQUIRIES.find(t=>t.id===o.template);if(!o||!t||!t.products.includes(a.item)||PLANS[a.plan].output!==a.item)break;if(runningJobs(g).length>=8){message='Finish some work before accepting more than eight open jobs.';break;}const value=quoteValue(g,t,o.qty,a.item,a.terms),deposit=Math.round(value*.3),eng=engineeringHours(g,t,a.item);const j:WorkOrder={id:g.nextId++,name:t.name,client:t.client,kind:t.kind,part:partKey(t,a.item),item:a.item,qty:o.qty,value,deposit,accepted:g.time,due:g.time+t.days*8*(a.terms==='rush'?.65:a.terms==='flexible'?1.4:1),plan:a.plan,terms:a.terms,service:t.service,engineering:a.engineering,engineeringTotal:eng,engineeringLeft:eng,engineeringCharged:false,engineeringReady:false,qaLeft:t.service?.8:.3+o.qty*.08,released:false,paused:false,stage:'planning',transferBatch:0,tasks:t.service?[]:PLANS[a.plan].steps.map(([recipe,n])=>({recipe,total:n*o.qty,done:0})),bins:{},cost:0,finished:0,paid:0};g.jobs.push(j);g.offers=g.offers.filter(v=>v.id!==o.id);receive(g,deposit,'Customer deposit',`${t.client}: ${t.name}`);ok=true;message='Order accepted. Choose its process route, reserve materials, and release it to the shop.';break;}
 case'release':if(job&&job.stage==='planning'){job.released=true;ok=true;message='Job released. Engineering, production, and inspection share your available people.';}break;
 case'pauseJob':if(job&&job.stage!=='complete'&&job.stage!=='shipping'){job.paused=!job.paused;ok=true;}break;
 case'prioritize':if(job&&job.stage!=='complete'){g.jobs=[job,...g.jobs.filter(j=>j.id!==job.id)];ok=true;}break;
 case'dispatch':if(job)ok=dispatch(g,job);break;
 case'jobRoute':if(job&&job.stage==='planning'&&!Object.values(job.bins).some(b=>Object.values(b).some(n=>n!>0))&&!g.moves.some(m=>m.job===job.id)&&PLANS[a.plan].output===job.item){job.plan=a.plan;job.tasks=PLANS[a.plan].steps.map(([recipe,n])=>({recipe,total:n*job.qty,done:0}));ok=true;}else message='Select the route before reserving material or releasing work.';break;
 case'engineeringMode':if(job&&!job.engineeringReady&&!job.engineeringCharged){job.engineering=a.mode;ok=true;}break;
 case'batchSize':if(job&&job.stage!=='complete'){job.transferBatch=a.qty;ok=true;}break;
 case'supplyJob':{if(!job||job.service||job.stage==='complete')break;const needs=jobMissing(g,job),price=needs.reduce((n,m)=>n+Math.max(0,m.qty-(g.inventory[m.item]||0))*ITEMS[m.item].buy*PRICE,0)*(a.express?1.2:1);if(!needs.length){message='The planned material is already reserved, consumed, or on order.';break;}if(!pay(g,Math.ceil(price),'Materials',`Material for ${job.name}${a.express?' · express':''}`,job))break;for(const need of needs){const fromStock=Math.min(need.qty,g.inventory[need.item]||0);g.inventory[need.item]=(g.inventory[need.item]||0)-fromStock;job.bins.stores??={};job.bins.stores[need.item]=(job.bins.stores[need.item]||0)+fromStock;job.cost+=fromStock*ITEMS[need.item].buy*PRICE;const qty=need.qty-fromStock;if(qty)g.moves.push({id:g.nextId++,job:job.id,item:need.item,qty,from:'supplier',to:'stores',start:g.time,end:g.time+(a.express?.5:2),kind:'purchase'});}ok=true;message=`Materials reserved. Purchased items arrive in ${a.express?'half an hour':'two working hours'}.`;break;}
 case'borrow':if(g.debt+a.amount<=creditLimit(g)){g.debt+=a.amount;receive(g,a.amount,'Financing','Working-capital draw');ok=true;}else message='That draw exceeds your credit line.';break;
 case'repay':{const amount=Math.min(a.amount,g.debt);if(amount&&g.cash>=amount){g.cash-=amount;g.debt-=amount;log(g,-amount,'Financing','Loan principal repaid');ok=true;}break;}
 case'rename':g.name=a.name.trim();ok=true;break;
 case'buyStock':if(ITEMS[a.item].buy&&pay(g,ITEMS[a.item].buy*PRICE*a.qty,'Materials',`Stock purchase: ${ITEMS[a.item].short}`)){g.moves.push({id:g.nextId++,job:0,item:a.item,qty:a.qty,from:'supplier',to:'stores',start:g.time,end:g.time+2,kind:'purchase'});ok=true;}break;
 case'sellStock':{const qty=Math.min(a.qty,g.inventory[a.item]||0),price=ITEMS[a.item].sell?ITEMS[a.item].sell*PRICE:ITEMS[a.item].buy*PRICE*.5;if(qty&&price){g.inventory[a.item]=(g.inventory[a.item]||0)-qty;receive(g,Math.round(qty*price),'Stock sale',`${qty} ${ITEMS[a.item].short}`);g.revenue+=Math.round(qty*price);ok=true;}break;}
 case'stockLot':if(runningJobs(g).length<8&&PLANS[a.plan].output===a.item&&ITEMS[a.item].sell){g.jobs.push({id:g.nextId++,name:`House catalog: ${ITEMS[a.item].short}`,client:g.name,kind:'stock',part:'house:'+a.item,item:a.item,qty:a.qty,value:0,deposit:0,accepted:g.time,due:g.time+800,plan:a.plan,terms:'standard',service:false,engineering:'inhouse',engineeringTotal:0,engineeringLeft:0,engineeringCharged:false,engineeringReady:true,qaLeft:.2+a.qty*.06,released:false,paused:false,stage:'planning',transferBatch:0,tasks:PLANS[a.plan].steps.map(([recipe,n])=>({recipe,total:n*a.qty,done:0})),bins:{},cost:0,finished:0,paid:0});ok=true;message='House production lot created. Release it like any other work order.';}break;
 }
 if(ok)pump(g);return{state:g,ok,message:message||(ok?'':'Not enough cash, capacity, or eligible work for that action.')};}
export function jobBlocker(g:Career,j:WorkOrder){if(j.paused)return 'Held by you';if(j.stage==='planning')return 'Choose a route and release the work order';if(j.stage==='engineering')return engineeringBlocked(g,j)||'Engineering in progress';if(j.stage==='inspection')return freeWorkers(g,'inspector').length?'Final inspection in progress':'Waiting for an inspector or the owner';if(j.stage==='ready')return 'Ready to dispatch';if(j.stage==='shipping')return 'Shipping to customer';if(j.stage==='complete')return 'Delivered';const missing=neededEquipment(g,j.plan);if(missing.length)return 'Missing '+missing.map(id=>MACHINES[id].short).join(', ');if(g.work.some(w=>w.job===j.id))return 'Operations underway';if(jobMissing(g,j).length)return 'Material still needs to be ordered or reserved';if(g.moves.some(m=>m.job===j.id))return 'Material in transit';return 'Waiting for available people, equipment, or processing funds';}
export function validCareer(value:unknown):value is Career {
 if(!value||typeof value!=='object')return false;const g=value as Career;
 const number=(v:unknown,max=1e14)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;
 const integer=(v:unknown,max=1e9)=>number(v,max)&&Number.isInteger(v);
 const text=(v:unknown,max=160)=>typeof v==='string'&&v.length<=max;
 const stock=(v:unknown)=>!!v&&typeof v==='object'&&Object.entries(v).every(([i,n])=>ITEM_IDS.includes(i as ItemId)&&integer(n,1e6));
 if(g.version!==1||!text(g.name,60)||!g.name.trim()||![g.time,g.cash,g.debt,g.arrears,g.revenue,g.expenses].every(v=>number(v))||!number(g.reputation,100)||!integer(g.nextId)||!integer(g.floor,2)||typeof g.cad!=='boolean'||typeof g.metrology!=='boolean'||typeof g.autoShip!=='boolean'||![...ROLE_IDS,'auto','office'].includes(g.owner)||!integer(g.delivered))return false;
 if(!Array.isArray(g.equipment)||g.equipment.length>bays(g)||!g.equipment.every(e=>e&&integer(e.id)&&e.id>0&&MACHINE_IDS.includes(e.type)&&!vendor(e.type)&&integer(e.bay,bays(g)-1)&&typeof e.used==='boolean'&&integer(e.level,2)&&number(e.paid)&&text(e.lastPart)&&text(e.lastRecipe)&&integer(e.completed)&&number(e.busy)&&typeof e.paused==='boolean')||new Set(g.equipment.map(e=>e.bay)).size!==g.equipment.length)return false;
 if(!Array.isArray(g.people)||g.people.length>24||!g.people.every(p=>p&&integer(p.id)&&p.id>0&&text(p.name,60)&&ROLE_IDS.includes(p.role)&&number(p.skill,3)&&p.skill>0&&number(p.wage,1000)&&integer(p.assignment)&&(!p.assignment||g.equipment.some(e=>e.id===p.assignment))&&number(p.hired)))return false;
 if(!Array.isArray(g.offers)||g.offers.length>10||!g.offers.every(o=>o&&integer(o.id)&&o.id>0&&INQUIRIES.some(t=>t.id===o.template)&&integer(o.qty,100)&&o.qty>0&&number(o.created)&&number(o.expires)&&o.expires>=o.created&&typeof o.repeat==='boolean'))return false;
 if(!Array.isArray(g.jobs)||g.jobs.length>100||runningJobs(g).length>8||!g.jobs.every(j=>j&&integer(j.id)&&j.id>0&&text(j.name)&&text(j.client)&&Object.hasOwn(KIND_NAMES,j.kind)&&text(j.part)&&ITEM_IDS.includes(j.item)&&integer(j.qty,100)&&j.qty>0&&[j.value,j.deposit,j.accepted,j.due,j.engineeringTotal,j.engineeringLeft,j.qaLeft,j.cost,j.finished,j.paid].every(v=>number(v))&&j.deposit<=j.value&&Object.hasOwn(PLANS,j.plan)&&PLANS[j.plan].output===j.item&&['flexible','standard','rush'].includes(j.terms)&&['inhouse','partner'].includes(j.engineering)&&[j.service,j.engineeringCharged,j.engineeringReady,j.released,j.paused].every(v=>typeof v==='boolean')&&['planning','engineering','production','inspection','ready','shipping','complete'].includes(j.stage)&&[0,1,5,10].includes(j.transferBatch)&&Array.isArray(j.tasks)&&j.tasks.length<=10&&j.tasks.every(t=>t&&Object.hasOwn(RECIPES,t.recipe)&&integer(t.total,200)&&integer(t.done,t.total))&&j.bins&&Object.entries(j.bins).every(([loc,b])=>text(loc,30)&&stock(b))))return false;
 if(!Array.isArray(g.work)||g.work.length>24||!g.work.every(w=>w&&integer(w.id)&&w.id>0&&g.jobs.some(j=>j.id===w.job&&integer(w.task,j.tasks.length-1))&&integer(w.equipment)&&(!w.equipment||g.equipment.some(e=>e.id===w.equipment))&&(w.vendor===null||w.vendor==='outside'||w.vendor==='partner')&&Number.isInteger(w.worker)&&(w.worker===-1||w.worker===0||g.people.some(p=>p.id===w.worker))&&integer(w.qty,200)&&w.qty>0&&number(w.start)&&number(w.finish)&&w.finish>=w.start))return false;
 if(!Array.isArray(g.moves)||g.moves.length>500||!g.moves.every(m=>m&&integer(m.id)&&m.id>0&&(m.job===0||g.jobs.some(j=>j.id===m.job))&&ITEM_IDS.includes(m.item)&&integer(m.qty,200)&&m.qty>0&&text(m.from,30)&&text(m.to,30)&&number(m.start)&&number(m.end)&&m.end>=m.start&&['feed','purchase','shipment'].includes(m.kind)))return false;
 if(!stock(g.inventory)||!Array.isArray(g.drawings)||g.drawings.length>100||!g.drawings.every(d=>d&&text(d.part)&&text(d.name)&&ITEM_IDS.includes(d.item)&&Object.hasOwn(KIND_NAMES,d.origin)&&number(d.created)&&integer(d.runs)))return false;
 if(!Array.isArray(g.ledger)||g.ledger.length>120||!g.ledger.every(l=>l&&integer(l.id)&&number(l.time)&&typeof l.amount==='number'&&Number.isFinite(l.amount)&&Math.abs(l.amount)<1e14&&text(l.category,60)&&text(l.text,300)))return false;
 if(!Array.isArray(g.history)||g.history.length>60||!g.history.every(h=>h&&integer(h.day)&&[h.cash,h.revenue,h.expenses].every(n=>number(n))))return false;
 const ids=[...g.equipment,...g.people,...g.offers,...g.jobs,...g.work,...g.moves,...g.ledger].map(v=>v.id);return new Set(ids).size===ids.length&&ids.every(id=>id<g.nextId);
}
